### ISSUE TITLE
Table not saved

### ISSUE THREAD

**Issue by gorje001** [satyan/sugar#135]
Sugar is not saving my db table.  I see the .db files and in sqlite3 there are no tables.  The output of the .save() method in logcat is
08-08 17:05:20.242    1800-1814/com.xxxxxx.android.api.debug.test I/Sugar﹕ ApiCacheTable saved : -1

When I try to query the table I get 'no such table: API_CACHE_TABLE.
I have a default constructor in my entity class.  The manifest is filled in as in the documentation.
Here is more logcat on the save.
08-08 17:15:45.422    1898-1911/com.sportngin.android.api.debug.test E/SQLiteLog﹕ (1) no such table: API_CACHE_TABLE
08-08 17:15:45.432    1898-1911/com.sportngin.android.api.debug.test E/SQLiteDatabase﹕ Error inserting TIMESTAMP=1407532370385 MODEL_NAME=TestModel JSON={"something":"some string","num":3.76,"id":57,"modelName":"TestModel","timestamp":1407532370385} PARAM_HASH_CODE=597860099
    android.database.sqlite.SQLiteException: no such table: API_CACHE_TABLE (code 1): , while compiling: INSERT INTO API_CACHE_TABLE(TIMESTAMP,MODEL_NAME,JSON,PARAM_HASH_CODE) VALUES (?,?,?,?)
            at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
            at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
            at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
            at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
            at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
            at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
            at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1467)
            at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1339)
            at com.orm.SugarRecord.save(SugarRecord.java:126)
            at com.orm.SugarRecord.save(SugarRecord.java:45)

**Comment by farmazon3000** [comment]
was this added to documentation or faq?
