### ISSUE TITLE
null value for Date field cause app to crash

### ISSUE THREAD

**Issue by pocha** [satyan/sugar#178]
I had class with default value of Date field set to null. On saving object of the class, an error is thrown on SugarRecord.java line 109.

**Comment by pasmontesinos** [comment]
I have the same problem with date field. I've deleted the compile dependence for sugar 1.3 on gradle and I've added the sugar-1.4_beta.jar in my libs folder on Android Studio, but continue the problem.

     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'long java.util.Date.getTime()' on a null object reference
            at com.orm.SugarRecord.save(SugarRecord.java:109)
            at com.orm.SugarRecord.save(SugarRecord.java:45)

Should I do else?

**Comment by pasmontesinos** [comment]
It works!!

Sorry, I did not included this:
compile files('libs/sugar-1.4_beta.jar')
