### ISSUE TITLE
No such column error

### ISSUE THREAD

**Issue by charles-d-burton** [satyan/sugar#226]
I'm running into a no such column error in my code that according to the docs shouldn't be happening.  Here's the tables object definition.
````
public class TripRow extends SugarRecord<TripRow> {

    public String address;
    public double distance = 0;
    public String units = "km";

    //Relationship to a trip_group.  Meaning a collection of trips that are logically grouped together.
    //I may add additional columns for groups later.
    public TripGroup trip_group;

    public TripRow(String address, double distance, TripGroup trip_group) {
        this.address = address;
        this.distance = distance;
        this.trip_group = trip_group;
    }

    public TripRow() {

    }
}
````

When I try to load it with the following statement I get a no such column exception.

````
String entries[] = {Long.toString(group.getId())};
                //List<TripRow> rows = TripRow.listAll(TripRow.class);

                List<TripRow> rows = TripRow.find(TripRow.class, "trip_group = ? ORDER BY id DESC", entries);
````

Here's the exception:

````
 Caused by: android.database.sqlite.SQLiteException: no such column: trip_group (code 1): , while compiling: SELECT * FROM TRIP_ROW WHERE trip_group = ? ORDER BY id DESC
            at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
            at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1113)
            at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:690)
            at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
            at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
            at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
            at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
            at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1448)
            at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1295)
            at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1166)
            at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1372)
            at com.orm.SugarRecord.find(SugarRecord.java:208)
            at com.orm.SugarRecord.find(SugarRecord.java:172)
````

**Comment by agustinm20** [comment]
On the public class change this:
public TripGroup tripGroup;

**Comment by charles-d-burton** [comment]
That's what I ended up doing and it worked.  The problem is that I don't have any way to examine the schema that I can find and I had to drop the database because I couldn't write a migration script.

**Comment by black-snow** [comment]
That's quite a major issue. Why can't `my_identifier` be found as `my_identifier`. I'd like to use the same name in my query strings as in my model class.

**Comment by alaaghribi** [comment]
Can't we simply ignore the SugarORM specification and let it create columns exactly as the variables in the model class ?

**Comment by sibeliusseraphini** [comment]
maybe we should rethink how Sugar creates or transform collums names

**Comment by black-snow** [comment]
ORMs I know stick to the following convention:

* Columns are all in lower case.
* Transform camel case to snake case: 
customersThatAreImportant => customers_that_are_important
OtherCustomers => other_customers
* Snake case stays as it is: emails_sent => emails_sent

The algorithm is quite simple; just transform any upper case letter to its lower case version and put an underscore before it unless it's the very first char. Some won't put underscores before multiple uppercase letters that are right next to each other, e. g. numSMS => num_sms

**Comment by sibeliusseraphini** [comment]
@black-snow feel free to submit a pull request for this.

One problem that I think is how to migrate from an older version of sugar that is using the other column name convention, do you have an idea?

**Comment by black-snow** [comment]
@sibeliusseraphini I ain't got no better solution than shipping this with a major release that might not be backwards compatible with the previous major version.

But let's rethink this. The original issue was (for me) that I had to use different column names in my queries. Actually I don't care what names the columns have as long as I can use the same identifier across all parts of the ORM on my layer (as long as I don't need to write queries by hand). Isn't the real issue that the experience is just not consistent? Assuming I have a field `String emailAddress`, I'd expect `MyModel.find(MyModel.class, "emailAddress = ?", ...)` to be exactly what I need to do. Isn't Sugar evaluating column names in where clauses? I quickly scanned through the code but didn't find where `query()` happens.

**Comment by larrytech7** [comment]
i think there might be a problem with the representation of fields like this: my_id. It doesn't really translate to a field 'my_id' in the database. I get a 'No such column' error for a filed like 'my_id'

**Comment by xxkfjfredxx** [comment]
i have the similar problem

**Comment by larrytech7** [comment]
In the mean time i think it would be best to use filed names in camel case in order that they properly translate by sugar to the underscore notation. SQL is a little bit sensitive to column names such as those i guess.
