### ISSUE TITLE
java.lang.NullPointerException issue

### ISSUE THREAD

**Issue by eman1986** [satyan/sugar#234]
I'm having some trouble listing all of my data. every time it gets to the following code I get a java.lang.NullPointerException  error.

```
List<Boards> boards = Boards.listAll(com.eds.billboard.model.Boards.class);
```

I'm hoping someone can help me with this.

Thanks

**Comment by balazsmaria** [comment]
I had also problems with that in 1.3 but could you please post the stacktrace to see what's going on and where?

**Comment by eGorets** [comment]
+1

**Comment by jmate003** [comment]
Having the same issue here. It started on Thursday and I've been using Sugar ORM for about 5 months now.

**Comment by jmate003** [comment]
I was able to solve my issue. I'm going to post it just in case someone else runs into the same issue. It was a stupid mistake. Basically I'm extending the Sugar app class and removed super in onCreate by mistake.

**Comment by eGorets** [comment]
my solution.i just upgrade db version in manifest to 2.

**Comment by eman1986** [comment]
Here's my stack trace

````
18406-18406/com.eds.bills E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.eds.bills, PID: 18406
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.eds.bills/com.eds.bills.Boards}: java.lang.NullPointerException
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2334)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2392)
            at android.app.ActivityThread.access$900(ActivityThread.java:169)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1280)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:146)
            at android.app.ActivityThread.main(ActivityThread.java:5487)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.NullPointerException
            at com.orm.SugarRecord.find(SugarRecord.java:204)
            at com.orm.SugarRecord.listAll(SugarRecord.java:134)
            at com.eds.bills.Boards.PopulateBoardList(Boards.java:138)
            at com.eds.bills.Boards.onCreate(Boards.java:29)
            at android.app.Activity.performCreate(Activity.java:5451)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2298)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2392)
            at android.app.ActivityThread.access$900(ActivityThread.java:169)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1280)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:146)
            at android.app.ActivityThread.main(ActivityThread.java:5487)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
            at dalvik.system.NativeStart.main(Native Method)
```

**Comment by eman1986** [comment]
I finally figured it out, I forgot to add the following to my manifest file

```
android:name="com.orm.SugarApp"
```

added that and now it works.

**Comment by BenLorenzo** [comment]
yo eman thank you.. we have same problem. now its ok..

**Comment by dab13491** [comment]
Thanks eman !
