### ISSUE TITLE
Warning when application opens (Float cannot be cast to Integer)

### ISSUE THREAD

**Issue by SwiTool** [satyan/sugar#247]
Hi,

in version 1.3, when I run my application, i get this message in the console :

```
01-28 14:28:11.802  13190-13190/epitech.epiandroid W/Bundle﹕ Key VERSION expected Integer but value was a java.lang.Float.  The default value 0 was returned.
01-28 14:28:11.812  13190-13190/epitech.epiandroid W/Bundle﹕ Attempt to cast generated internal exception:
    java.lang.ClassCastException: java.lang.Float cannot be cast to java.lang.Integer
            at android.os.Bundle.getInt(Bundle.java:1000)
            at android.os.Bundle.getInt(Bundle.java:982)
            at com.orm.SugarConfig.getMetaDataInteger(SugarConfig.java:91)
            at com.orm.SugarConfig.getDatabaseVersion(SugarConfig.java:48)
            at com.orm.SugarDb.<init>(SugarDb.java:27)
            at com.orm.Database.<init>(Database.java:12)
            at com.orm.SugarApp.onCreate(SugarApp.java:11)
            at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1025)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4581)
            at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
            at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)
            at android.app.ActivityThread.handleBindApplication(Native Method)
            at android.app.ActivityThread.access$1600(ActivityThread.java:161)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1325)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:157)
            at android.app.ActivityThread.main(ActivityThread.java:5356)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
            at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
            at dalvik.system.NativeStart.main(Native Method)
```

Can you tell me if you are responsible for this error or tell me if I missed a step ?

Thanks

**Comment by bytehala** [comment]
Are you using decimals for your DB version?

**Comment by SwiTool** [comment]
Yes, I saw a tutorial with "0.1", I pasted without a think..
Thank you
