### ISSUE TITLE
no such table: A

### ISSUE THREAD

**Issue by black-snow** [satyan/sugar#313]
Hi,

I got crash logs from the Google Play Store telling me this:

```
Caused by: android.database.sqlite.SQLiteException: no such table: A (code 1): , while compiling: SELECT * FROM A WHERE pathlocal <> '' ORDER BY ID DESC
at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1316)
at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1255)
```

And indeed there is no table **A**. Sugar ORM runs fine on my test devices. An alpha user got this after updating from play store. 
Any guesses where the **A** comes from?

**Comment by black-snow** [comment]
Ah, wait a second, I think it's due to proguard obfuscating stuff - let me check that.

**Comment by black-snow** [comment]
Okay, I added `-keep class my.package.DbModel` to my proguard file and now I get a different error message:

```
Caused by: android.database.sqlite.SQLiteException: duplicate column name: B (code 1): , while compiling: CREATE TABLE DbModel
```

So I guess it's proguard.

@satyan you should add proguard settings to the wiki/docs

PS: actual model name replaced

**Comment by black-snow** [comment]
Now I'm trying with
```
-keepnames class de.berlitec.infinisee.database.DbModel {
    *;
}
-keepclassmembernames class de.berlitec.infinisee.database.DbModel {
    *;
}
```

**Comment by pavan-techmorphosis** [comment]
did this work for you ? I still get the error

**Comment by pavan-techmorphosis** [comment]
This worked for me - 
-keep class my.package.DbModel { *; }

**Comment by black-snow** [comment]
Keep wasn't enough for me - still got crashes. Seems to work w/ keepnames

**Comment by DVassilev** [comment]
@black-snow What was your final config?

**Comment by black-snow** [comment]
@DVassilev the one mentioned above worked for me

**Comment by sibeliusseraphini** [comment]
proguard related issues
