### ISSUE TITLE
java.lang.NoClassDefFoundError: javax/annotation/ParametersAreNonnullByDefault in 4.0.3 ICS

### ISSUE THREAD

**Issue by LOG-TAG** [satyan/sugar#344]
I'm getting java.lang.NoClassDefFoundError: javax/annotation/ParametersAreNonnullByDefault in 4.0.3 ICS, in L it works fine !! finally changed my sugar Lib to older version which works fine in ICS!!

E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.NoClassDefFoundError: javax/annotation/ParametersAreNonnullByDefault
            at java.lang.Class.isDeclaredAnnotationPresent(Native Method)
            at java.lang.Class.isAnnotationPresent(Class.java:1176)
            at com.orm.util.ReflectionUtil.getDomainClass(ReflectionUtil.java:278)
            at com.orm.util.ReflectionUtil.getDomainClasses(ReflectionUtil.java:254)
            at com.orm.SchemaGenerator.createDatabase(SchemaGenerator.java:37)
            at com.orm.SugarDb.onCreate(SugarDb.java:26)
            at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:165)
            at com.orm.SugarDb.getDB(SugarDb.java:36)
            at com.orm.SugarRecord.find(SugarRecord.java:189)
            at com.orm.SugarRecord.listAll(SugarRecord.java:94)
            at br.trackerexpense.expense.ExpenseListFragment.Set_Referash_Data(ExpenseListFragment.java:252)
            at br.trackerexpense.expense.ExpenseListFragment.onCreateView(ExpenseListFragment.java:87)
            at android.support.v4.app.Fragment.performCreateView(Fragment.java:1789)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:955)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1138)
            at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:740)
            at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1501)
            at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:551)
            at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1136)
            at android.app.Activity.performStart(Activity.java:4479)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1941)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1993)
            at android.app.ActivityThread.access$600(ActivityThread.java:127)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1159)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4507)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:978)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:745)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.ClassNotFoundException: javax.annotation.ParametersAreNonnullByDefault
            at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:61)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
            at java.lang.Class.isDeclaredAnnotationPresent(Native Method)
            at java.lang.Class.isAnnotationPresent(Class.java:1176)
            at com.orm.util.ReflectionUtil.getDomainClass(ReflectionUtil.java:278)
            at com.orm.util.ReflectionUtil.getDomainClasses(ReflectionUtil.java:254)
            at com.orm.SchemaGenerator.createDatabase(SchemaGenerator.java:37)
            at com.orm.SugarDb.onCreate(SugarDb.java:26)
            at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:165)
            at com.orm.SugarDb.getDB(SugarDb.java:36)
            at com.orm.SugarRecord.find(SugarRecord.java:189)
            at com.orm.SugarRecord.listAll(SugarRecord.java:94)
            at br.trackerexpense.expense.ExpenseListFragment.Set_Referash_Data(ExpenseListFragment.java:252)
            at br.trackerexpense.expense.ExpenseListFragment.onCreateView(ExpenseListFragment.java:87)
            at android.support.v4.app.Fragment.performCreateView(Fragment.java:1789)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:955)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1138)
            at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:740)
            at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1501)
            at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:551)
            at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1136)
            at android.app.Activity.performStart(Activity.java:4479)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1941)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1993)
            at android.app.ActivityThread.access$600(ActivityThread.java:127)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1159)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4507)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:978)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:745)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by nicolabeghin** [comment]
any news about this?

**Comment by adin234** [comment]
any updates?

**Comment by nicolabeghin** [comment]
up

**Comment by thanhtanh** [comment]
Got same error here. Android 4.1.1

**Comment by adin234** [comment]
@thanhtanh i think i fixed this through the manifest, i forgot to put the proper entries in my android manifest

**Comment by Gokuldroid** [comment]
What did you do with android manifest?

**Comment by rhalfi** [comment]
I know this is old but in case somebody still needs this the fix is to put in the manifest 
<meta-data android:name="DOMAIN_PACKAGE_NAME" android:value="YOUR PKG NAME" />
