### ISSUE TITLE
java.lang.NoClassDefFoundError: com.orm.SugarDb

### ISSUE THREAD

**Issue by agoransson** [satyan/sugar#360]
I get this error on android devices running 4.4, there's no problems with 5.0+. Do you have any idea what the cause may be? It's pointing to the line `super.onCreate()` in the app class.

    java.lang.NoClassDefFoundError: com.orm.SugarDb
      at com.orm.Database.<init>(Database.java:12)
      at com.orm.SugarApp.onCreate(SugarApp.java:11)
      at com.myapp.MyApp.onCreate(MyApp.java:15)
      at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4729)
      at android.app.ActivityThread.access$1600(ActivityThread.java:174)
      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1367)
      at android.os.Handler.dispatchMessage(Handler.java:102)
      at android.os.Looper.loop(Looper.java:146)
      at android.app.ActivityThread.main(ActivityThread.java:5593)
      at java.lang.reflect.Method.invokeNative(Native Method)
      at java.lang.reflect.Method.invoke(Method.java:515)
      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
      at dalvik.system.NativeStart.main(Native Method)

Here's is the app class.

    public class MyApp extends SugarApp {
      @Override
      public void onCreate() {
        super.onCreate();

        // configure Flurry
        FlurryAgent.setLogEnabled(false);

        // init Flurry
        FlurryAgent.init(this, VERSION.FLURRY);

        // Adjust SDK
        AdjustConfig config = new AdjustConfig(this, VERSION.ADJUST, VERSION.ADJUST_ENV);
        Adjust.onCreate(config);
      }
    }

And the gradle import - we're using 1.3

    compile 'com.github.satyan:sugar:1.3'

**Comment by agoransson** [comment]
I believe this error was caused by a number of things, for one I had a custom application class that extended SugarApp, while I actually needed it to extend MultiDexApplication.

There is a way to init the SugarContext without extending the SugarApp, but that is not possible with just the gradle imports. My solution was to clone the repository and add the library to my own app. Then following this pattern to init SugarORM.

    public class ClientApp extends Application {
        @Override
        public void onCreate() {
            super.onCreate();
            SugarContext.init(this);
        }

        @Override
        public void onTerminate() {
            super.onTerminate();
            SugarContext.terminate();
        }
    }

I haven't managed to get this tested properly yet, but the initial tests on emulators running API 19 seem positive.

So, in the end it was not an error with the library it self - it was a problem with the gradle versions not being up to date with the source code.

**Comment by phanii** [comment]
hi ,
i'm also facing the same problem , i think the problem with the module set up config. file ,
Any Help ??
