### ISSUE TITLE
item can't update!

### ISSUE THREAD

**Issue by SmileYangs** [satyan/sugar#368]
code : 
```java 
Item item = Item.findById(Item.class, id);
tem.done = checkBox.isChecked();
```

error 

```java
07-30 01:54:24.861  17322-17331/? E/art﹕ Failed sending reply to debugger: Broken pipe
07-30 01:54:26.945  17322-17322/com.yuxian.simpletodo E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.yuxian.simpletodo, PID: 17322
    java.lang.NullPointerException: Attempt to write to field 'boolean com.yuxian.todoModel.Item.done' on a null object reference
            at com.yuxian.simpletodo.MainActivity$3.onItemClick(MainActivity.java:119)
            at android.widget.AdapterView.performItemClick(AdapterView.java:305)
            at android.widget.AbsListView.performItemClick(AbsListView.java:1146)
            at android.widget.AbsListView$PerformClick.run(AbsListView.java:3053)
            at android.widget.AbsListView$3.run(AbsListView.java:3860)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

```

**Comment by agoransson** [comment]
Looks like it doesn't find the item, are you sure the id is correct?
