### ISSUE TITLE
Proguard - Table A Already Exists

### ISSUE THREAD

**Issue by DVassilev** [satyan/sugar#395]
Hi,

When I use Proguard I get the following error:

```
android.database.sqlite.SQLiteException: table A already exists (code 1): , while compiling: CREATE TABLE A ( ID INTEGER PRIMARY KEY AUTOINCREMENT , C TEXT, D TEXT, E TEXT, F TEXT, G TEXT UNIQUE, H INTEGER NULL, I INTEGER )
       at android.database.sqlite.SQLiteConnection.nativePrepareStatement(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
       at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
       at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
       at android.database.sqlite.SQLiteProgram.(SQLiteProgram.java:58)
       at android.database.sqlite.SQLiteStatement.(SQLiteStatement.java:31)
       at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1672)
       at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1603)
       at com.orm.SugarDb.getDomainClasses()
       at com.orm.SugarDb.getDomainClasses()
       at com.orm.SugarDb.onCreate()
       at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:252)
       at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:164)
       at com.orm.Database.getDB()
       at com.orm.SugarRecord.save()
       etc...
```

I have in my Proguard config:

```
-keepattributes *Annotation*
-keepattributes Signature
-keep class mypackage.models.DbModel { *; }
-keepnames class mypackage.models.DbModel { *; }
-keepclassmembernames class mypackage.models.DbModel { *; }
```

However, it is still not working. I have tried incrementing version, changing database name, clearing data, reinstalling etc. but nothing is working.

Does anyone have any idea what the fix may be?

Thanks,
Daniel

**Comment by DVassilev** [comment]
Fixed it with this config:

```
-keep public class * extends com.orm.SugarRecord
-keep class com.orm.** { *; }
```

Should perhaps mention what proguard config is needed by the library.

**Comment by StefanFaulhaber** [comment]
This didn't quite did the trick for me, but this solved it:

-keepclasseswithmembernames public class * extends com.orm.SugarRecord { *; }
-keepclasseswithmembernames class com.orm.** { *; }

Mind the expression in the curly braces at the end of the first line.
