### ISSUE TITLE
java.lang.NoClassDefFoundError: com.orm.SugarDb

### ISSUE THREAD

**Issue by srinivas69** [satyan/sugar#412]
Hi,

I'm using the sugar orm in my application. 
Every thing seems to be fine with Android L, but when I try to run the same application it crashes saying NoClassDefFoundError.

10-31 19:34:44.612    1196-1196/? E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: in.co.ybn.rancho, PID: 1196
    java.lang.NoClassDefFoundError: com.orm.SugarDb
            at com.orm.Database.<init>(Database.java:12)
            at com.orm.SugarApp.onCreate(SugarApp.java:11)
            at in.co.ybn.rancho.application.RanchoApplication.onCreate(RanchoApplication.java:24)
            at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4328)
            at android.app.ActivityThread.access$1500(ActivityThread.java:135)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5001)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
            at dalvik.system.NativeStart.main(Native Method)

How to resolve it.

**Comment by sibeliusseraphini** [comment]
it's fixed on master

**Comment by sidhantpanda** [comment]
I am still facing this same issue on Android 4.4 in a MultiDex app. I am using version 1.4

**Comment by sachinletsgo** [comment]
I am stilling facing error

**Comment by sidhantpanda** [comment]
Hey @sachinletsgo 

What buildToolsVersion are you using? I was facing this error with 23.0.2
I switched back to 23.0.1 and its working fine now

**Comment by davidhowe** [comment]
Using buildtools 23.0.1 did NOT work for me. Also using version 1.4 in a multidex app, however it seems Android OS version specific. I experienced this issue on OS 4.4.4 Samsung TAB 3. No issue on my Samsung S5 OS 5.1.1

**Comment by TheZoker** [comment]
@satyan @JonatanSalas Have the same issue, running buildToolsVersion "23.0.3" and Sugar 1.4

**Comment by sidhantpanda** [comment]
Try using the master version. Instructions here :  [https://android-arsenal.com/details/1/337](https://android-arsenal.com/details/1/337)

**Comment by mohamadhadibi** [comment]
I have the same issue ver 1.5 with build tool 25.0.0

**Comment by jppasa** [comment]
Same issue for Android 4.4 using build tools 25.0.2

**Comment by quensh93** [comment]
same on buildToolsVersion '26.0.2' android 4.2
