### ISSUE TITLE
sqLiteDatabase not closed but it's Closeable

### ISSUE THREAD

**Issue by Ewg777** [satyan/sugar#426]
```java
 A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
    java.lang.Throwable: Explicit termination method 'close' not called
            at dalvik.system.CloseGuard.open(CloseGuard.java:184)
            at android.database.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:170)
            at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:190)
            at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
            at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
            at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
            at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:829)
            at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:814)
            at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:709)
            at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:1040)
            at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:256)
            at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:224)
            at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:164)
            at com.orm.SugarDb.getDB(SugarDb.java:36)
            at com.orm.SugarRecord.find(SugarRecord.java:189)
            at com.orm.SugarRecord.findById(SugarRecord.java:102)
```

**Comment by sibeliusseraphini** [comment]
fixed with: https://github.com/satyan/sugar/commit/fff7ae0fb7e130926b0550657afb8ad9894bf80f
