### ISSUE TITLE
java.lang.NoClassDefFoundError: com.orm.SugarDb

### ISSUE THREAD

**Issue by sidhantpanda** [satyan/sugar#484]
```
java.lang.NoClassDefFoundError: com.orm.SugarDb
    at com.orm.SugarContext.<init>(SugarContext.java:18)
    at com.orm.SugarContext.init(SugarContext.java:30)
    at com.orm.SugarApp.onCreate(SugarApp.java:12)
    at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4440)
    at android.app.ActivityThread.access$1500(ActivityThread.java:141)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1272)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:136)
    at android.app.ActivityThread.main(ActivityThread.java:5113)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
    at dalvik.system.NativeStart.main(Native Method)
```

I am working on a Multi Dex project. Currently just overriding the `attachBaseContext()` in all activities:
```
@Override
protected void attachBaseContext(Context base) {
    super.attachBaseContext(base);
    MultiDex.install(this);
}
```

Issue found on a Xiaomi device with Android 4.4

**Comment by sidhantpanda** [comment]
UPDATE:
There is some issue with SugarORM not behaving nicely with `buildToolsVersion "23.0.2"`
I had to revert back to `buildToolsVersion "23.0.1"` to make it work again

**Comment by jd-alexander** [comment]
I'm also having this issue on Kit Kat devices. reverting build tools havent worked

**Comment by sibeliusseraphini** [comment]
try to use master version, instruction on README

**Comment by tobiasschuerg** [comment]
`buildToolsVersion "23.0.1"` not work for me either on Android 4.0.4

**Comment by jonisaa** [comment]
Which version of Android Studio are you running?

**Comment by sidhantpanda** [comment]
I ended up using the master version as @sibeliusseraphini suggested. I extended the Application class and followed the instructions [here](https://github.com/satyan/sugar#how-to-use-master-version).

**Comment by jonisaa** [comment]
Another way is to use[ jitpack](https://jitpack.io). It's more simple. 

This is the way to get a Git project into your build:

Step 1. Add the JitPack repository to your build file

    gradle

Add it in your root build.gradle at the end of repositories:

```gradle
	allprojects {
		repositories {
			...
			maven { url "https://jitpack.io" }
		}
	}
```

Step 2. Add the dependency

```gradle
	dependencies {
	        compile 'com.github.satyan:sugar:-SNAPSHOT'
	}
```
Well, I will close this Issue!

**Comment by rhomayouni** [comment]
it resolved when i removed 'multiDexEnabled true' from app.gradle
