### ISSUE TITLE
Database upgrade wipes all data 

### ISSUE THREAD

**Issue by refaelsh** [satyan/sugar#495]
Hello all,

I tried following this guide: http://satyan.github.io/sugar/migration.html
without any luck. Here is exactly what I did:
1. SugarORM version is 1.3.1
2. I created the sugar_upgrades folder in the assets folder.
3. I've put an empty 1.sql file in there.
4. I've also put 2.sql file in there, with the following contents:
alter table ENTRY add NOTE TEXT; (also tried it with an empty file).
5. I've changed VERSION (in AndroidManifest.xml) from 1 to 2.
6. Please take a look at the following Entry.java file. I was trying to add the "note" field to the ENTRY table (line 11 and 24): https://www.dropbox.com/s/49f8nvntyod28dk/Entry.java?dl=0.

I ran the app, and the database was wiped clean!

Please help Me figure it out, what am I missing?

Thanks. Refael.

**Comment by sibeliusseraphini** [comment]
@refaelsh I think this is fixed in the master version

Could you try to use the master version?

**Comment by refaelsh** [comment]
Tried it: if I put this line compile 'com.github.satyan:sugar:1.4'
the app would not even run!!! Its kinda hard to explain, but I get this message ("Message Gradle build"):

Error:Execution failed for task ':app:dexDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.8.0_60\bin\java.exe'' finished with non-zero exit value 2

Here is a link to a screenshot:
https://www.dropbox.com/s/9msrciwjy7guds0/Untitled.png?dl=0

**Comment by sibeliusseraphini** [comment]
follow the readme.md instruction to use master version instead of 1.4, the documentation is update

Update your plugins, you should try to use Android 2 (it is much better than the 1.x version)

I think this is related to a multidex problem, please include the full stack trace, only the last line is not enough to debug

**Comment by refaelsh** [comment]
Thank You sibeliusseraphini :-)

use master version instead of 1.4 - Tried it, "multidex problem" is gone, but now the SugarRecord Class is not found because "import com.orm.SugarRecord" is no longer recognized.

Update your plugins - updated.

you should try to use Android 2 - But it is still in Beta, I have a psychological barrier for Beta stuff :-)

please include the full stack trace - Here is the full stack trace: https://www.dropbox.com/s/dvr95egohhuo7cg/Full%20trace.txt?dl=0

**Comment by sibeliusseraphini** [comment]
@refaelsh this could help http://stackoverflow.com/questions/15209831/unable-to-execute-dex-method-id-not-in-0-0xffff-65536

**Comment by refaelsh** [comment]
@sibeliusseraphini 
Nice! Thank You! Using 1.4 does not produces the "multidex problem" anymore.

@To_Every_One
But now, what happens is that the first time I try to save() a new record, I get the following exception:
"table ENTRY has no column named NOTE" (please look at My original post, NOTE is a field I am trying to add too the ENTRY table).
Here is the full stack trace just in case:
https://www.dropbox.com/s/frzgavettnzqdc4/Full%20stack%20trace%202.txt?dl=0

**Comment by sibeliusseraphini** [comment]
I recommend you to use the debugger tool available on Android Studio to try to understand why this problem is happening, set some breakpoints

this only happen on a existing app? I think your database is not upgrading

The master version add new column automatically, and could resolve this problem

**Comment by refaelsh** [comment]
this only happen on a existing app? - It happens in onCreate(), the first two lines of onCreate are as follows:
Entry entry = new Entry(1, 1, true, "");
entry.save(); //It happens here.

I think your database is not upgrading - Yes, I think so too. Is it a bug in SugarORM or am I doing something wrong?

The master version add new column automatically, and could resolve this problem - Two problems with that:
1. Previous version don't do it? Only master version does it?
2. I've already tried it (as You suggested a few posts above) - "now the SugarRecord Class is not found because "import com.orm.SugarRecord" is no longer recognized.", I don't know what to do.

**Comment by jayeshcp** [comment]
Same problem, using Sugar ORM 1.4 version, Android Studio 2.1.1.

Added `String description;` together with its getter and setter, and changed db version from 3 to 4.

**AndroidManifest.xml**:

```xml
<meta-data android:name="VERSION" android:value="4"/>
```

**4.sql**:

```sql
alter table DECK add column DESCRIPTION text;
```

**Error log**:
    
```console
05-16 14:10:15.867 31622-31622/? E/SQLiteLog: (1) table DECK has no column named DESCRIPTION
05-16 14:10:15.867 31622-31622/? E/AndroidRuntime: FATAL EXCEPTION: main
   Process: com.jayeshcp.cards, PID: 31622
   android.database.sqlite.SQLiteException: table DECK has no column named DESCRIPTION (code 1): , while compiling: INSERT OR REPLACE  INTO DECK(TITLE,ID,DESCRIPTION) VALUES (?,?,?)
   #################################################################
   Error Code : 1 (SQLITE_ERROR)
   Caused By : SQL(query) error or missing database.
    (table DECK has no column named DESCRIPTION (code 1): , while compiling: INSERT OR REPLACE  INTO DECK(TITLE,ID,DESCRIPTION) VALUES (?,?,?))
   #################################################################
       at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
       at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1093)
       at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:670)
       at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
       at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:59)
       at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
       at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1607)
       at com.orm.SugarRecord.save(SugarRecord.java:266)
       at com.orm.SugarRecord.save(SugarRecord.java:360)
```
