### ISSUE TITLE
Unable to open database file (code 14)

### ISSUE THREAD

**Issue by howettl** [satyan/sugar#500]
I'm getting this error after making a large number of reads and writes to my db, which causes my app to crash.  It happens if I make ~10 000 reads/writes within about 5 - 10 minutes.  If the rate of read/writes is lower then the problem does not seem to occur.

Here is the stack trace:

java.lang.Error: FATAL EXCEPTION [IntentService[com.mycompany.myapp.programs.LoadProgramFileIntentService]]
Unity version     : 5.3.1p1
Device model      : HTC HTC One_M8
Device fingerprint: htc/htc_asia_hk/htc_m8:4.4.4/KTU84P/397296.4:user/release-keys
Caused by: android.database.sqlite.SQLiteCantOpenDatabaseException: unable to open database file (code 14)
     at android.database.sqlite.SQLiteConnection.nativeExecuteForLong(Native Method)
     at android.database.sqlite.SQLiteConnection.executeForLong(SQLiteConnection.java:634)
     at android.database.sqlite.SQLiteSession.executeForLong(SQLiteSession.java:652)
     at android.database.sqlite.SQLiteStatement.simpleQueryForLong(SQLiteStatement.java:107)
     at com.orm.SugarRecord.count(SugarRecord.java:237)
     at com.orm.SugarRecord.count(SugarRecord.java:209)
     at com.mycompany.myapp.model.ContentManager.countSync(ContentManager.java:532)
     at com.mycompany.myapp.account.AccountManager.isSignedInSync(AccountManager.java:54)
     at com.mycompany.myapp.programs.LoadProgramFileIntentService.onHandleIntent(LoadProgramFileIntentService.java:60)
     at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
     at android.os.Handler.dispatchMessage(Handler.java:102)
     at android.os.Looper.loop(Looper.java:157)
     at android.os.HandlerThread.run(HandlerThread.java:61)

Some quick googlng lead me to some posts about not closing cursors after using them, but I'm not sure if that is the source of this problem or not.

**Comment by howettl** [comment]
This turned out to be a problem with leaking file pointers elsewhere in my application.  It was coming up as a crash when I tried to access the database because that was the most frequent use of the file system.
