### ISSUE TITLE
Double-brace initialization triggers syntax error

### ISSUE THREAD

**Issue by iambmelt** [satyan/sugar#507]
A trivial example to repro what *looks* like a bug -- see `onResume()`

**AndroidManifest.xml**
```xml
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.sample.sugartest">

    <application
        android:name="com.orm.SugarApp"
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:supportsRtl="true"
        android:theme="@style/AppTheme">
        <activity android:name=".MainActivity">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>

        <!-- Sugar config -->
        <meta-data
            android:name="DATABASE"
            android:value="saccharine.db" />
        <meta-data
            android:name="VERSION"
            android:value="1" />
        <meta-data
            android:name="QUERY_LOG"
            android:value="true" />
        <meta-data
            android:name="DOMAIN_PACKAGE_NAME"
            android:value="com.example" />

    </application>
</manifest>
```

**Example Entity**
```java
public class Person extends SugarRecord {

    public Person(){}

    public String name;

}
```

**Example Activity**
```java
public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
    }

    @Override
    protected void onResume() {
        super.onResume();

        // works
        Person p = new Person();
        p.name = "Fred";
        p.save();

        // doesn't
        Person g = new Person(){{
            name = "Carl";
        }};

        g.save();
  }
}
```

**Stacktrace**
```
01-25 16:37:31.385 10831-10831/? I/art: Late-enabling -Xcheck:jni
01-25 16:37:31.480 10831-10831/com.example.sample.sugartest W/System: ClassLoader referenced unknown path: /data/app/com.example.sample.sugartest-1/lib/arm
01-25 16:37:31.633 10831-10831/com.example.sample.sugartest I/Sugar: domain class : 
01-25 16:37:31.638 10831-10831/com.example.sample.sugartest I/Sugar: domain class : Person
01-25 16:37:31.638 10831-10831/com.example.sample.sugartest I/Sugar: Create table
01-25 16:37:31.638 10831-10831/com.example.sample.sugartest D/Sugar: Fetching properties
01-25 16:37:31.640 10831-10831/com.example.sample.sugartest I/Sugar: Creating table 
01-25 16:37:31.640 10831-10831/com.example.sample.sugartest E/SQLiteLog: (1) near "(": syntax error
01-25 16:37:31.640 10831-10831/com.example.sample.sugartest W/System.err: android.database.sqlite.SQLiteException: near "(": syntax error (code 1): , while compiling: CREATE TABLE  ( ID INTEGER PRIMARY KEY AUTOINCREMENT , THIS0 , NAME TEXT )
01-25 16:37:31.641 10831-10831/com.example.sample.sugartest W/System.err:     at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
01-25 16:37:31.641 10831-10831/com.example.sample.sugartest W/System.err:     at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:887)
01-25 16:37:31.641 10831-10831/com.example.sample.sugartest W/System.err:     at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:498)
01-25 16:37:31.641 10831-10831/com.example.sample.sugartest W/System.err:     at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
01-25 16:37:31.641 10831-10831/com.example.sample.sugartest W/System.err:     at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
01-25 16:37:31.641 10831-10831/com.example.sample.sugartest W/System.err:     at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
01-25 16:37:31.641 10831-10831/com.example.sample.sugartest W/System.err:     at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1674)
01-25 16:37:31.641 10831-10831/com.example.sample.sugartest W/System.err:     at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1605)
01-25 16:37:31.641 10831-10831/com.example.sample.sugartest W/System.err:     at com.orm.SchemaGenerator.createTable(SchemaGenerator.java:161)
01-25 16:37:31.641 10831-10831/com.example.sample.sugartest W/System.err:     at com.orm.SchemaGenerator.createDatabase(SchemaGenerator.java:39)
01-25 16:37:31.641 10831-10831/com.example.sample.sugartest W/System.err:     at com.orm.SugarDb.onCreate(SugarDb.java:26)
01-25 16:37:31.641 10831-10831/com.example.sample.sugartest W/System.err:     at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:251)
01-25 16:37:31.641 10831-10831/com.example.sample.sugartest W/System.err:     at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
01-25 16:37:31.642 10831-10831/com.example.sample.sugartest W/System.err:     at com.orm.SugarDb.getDB(SugarDb.java:36)
01-25 16:37:31.642 10831-10831/com.example.sample.sugartest W/System.err:     at com.orm.SugarRecord.save(SugarRecord.java:360)
01-25 16:37:31.642 10831-10831/com.example.sample.sugartest W/System.err:     at com.example.sample.sugartest.MainActivity.onResume(MainActivity.java:27)
01-25 16:37:31.642 10831-10831/com.example.sample.sugartest W/System.err:     at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1258)
01-25 16:37:31.642 10831-10831/com.example.sample.sugartest W/System.err:     at android.app.Activity.performResume(Activity.java:6327)
01-25 16:37:31.642 10831-10831/com.example.sample.sugartest W/System.err:     at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3092)
01-25 16:37:31.642 10831-10831/com.example.sample.sugartest W/System.err:     at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3134)
01-25 16:37:31.642 10831-10831/com.example.sample.sugartest W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2481)
01-25 16:37:31.642 10831-10831/com.example.sample.sugartest W/System.err:     at android.app.ActivityThread.-wrap11(ActivityThread.java)
01-25 16:37:31.642 10831-10831/com.example.sample.sugartest W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
01-25 16:37:31.643 10831-10831/com.example.sample.sugartest W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
01-25 16:37:31.643 10831-10831/com.example.sample.sugartest W/System.err:     at android.os.Looper.loop(Looper.java:148)
01-25 16:37:31.643 10831-10831/com.example.sample.sugartest W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5417)
01-25 16:37:31.643 10831-10831/com.example.sample.sugartest W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
01-25 16:37:31.643 10831-10831/com.example.sample.sugartest W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
01-25 16:37:31.643 10831-10831/com.example.sample.sugartest W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
01-25 16:37:31.643 10831-10831/com.example.sample.sugartest I/Sugar: Create table
01-25 16:37:31.644 10831-10831/com.example.sample.sugartest D/Sugar: Fetching properties
01-25 16:37:31.644 10831-10831/com.example.sample.sugartest I/Sugar: Creating table PERSON
01-25 16:37:31.665 10831-10831/com.example.sample.sugartest I/Sugar: Person saved : 1
01-25 16:37:31.666 10831-10831/com.example.sample.sugartest E/SQLiteLog: (1) near "(": syntax error
01-25 16:37:31.666 10831-10831/com.example.sample.sugartest D/AndroidRuntime: Shutting down VM
01-25 16:37:31.668 10831-10831/com.example.sample.sugartest E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                   Process: com.example.sample.sugartest, PID: 10831
                                                                                   java.lang.RuntimeException: Unable to resume activity {com.example.sample.sugartest/com.example.sample.sugartest.MainActivity}: android.database.sqlite.SQLiteException: near "(": syntax error (code 1): , while compiling: INSERT OR REPLACE  INTO (THIS0,ID,NAME) VALUES (?,?,?)
                                                                                       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3103)
                                                                                       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3134)
                                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2481)
                                                                                       at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                       at android.os.Looper.loop(Looper.java:148)
                                                                                       at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                                    Caused by: android.database.sqlite.SQLiteException: near "(": syntax error (code 1): , while compiling: INSERT OR REPLACE  INTO (THIS0,ID,NAME) VALUES (?,?,?)
                                                                                       at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
                                                                                       at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:887)
                                                                                       at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:498)
                                                                                       at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
                                                                                       at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
                                                                                       at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
                                                                                       at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1469)
                                                                                       at com.orm.SugarRecord.save(SugarRecord.java:266)
                                                                                       at com.orm.SugarRecord.save(SugarRecord.java:360)
                                                                                       at com.example.sample.sugartest.MainActivity.onResume(MainActivity.java:34)
                                                                                       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1258)
                                                                                       at android.app.Activity.performResume(Activity.java:6327)
                                                                                       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3092)
                                                                                       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3134) 
                                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2481) 
                                                                                       at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                       at android.os.Looper.loop(Looper.java:148) 
                                                                                       at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 

```

**Comment by sibeliusseraphini** [comment]
@iambmelt what does ```{{ }}``` do?

do you really need it?

do you have any ideia of how to fix it?

**Comment by iambmelt** [comment]
@sibeliusseraphini For a more succinct explanation than I can give here, see [What is double-brace initialization?](http://stackoverflow.com/questions/1958636/what-is-double-brace-initialization-in-java)

>do you really need it?

Nope - but could be worth documenting since I ran into it.

>do you have any idea of how to fix it?

I haven't investigated - I wouldn't call this critical. Easy to work around :+1:

**Comment by sibeliusseraphini** [comment]
Could you try to use the Android debugging to try figure it out why this is happening?

I think when you use this syntax you have a **this0** field that is detected by the Sugar code. 

```sql
INSERT OR REPLACE  INTO (THIS0,ID,NAME) VALUES (?,?,?)
```

One way to fix could be to discard **THIS0** field

Now I remember about this syntax: [Every time someone uses double brace initialisation, a kitten gets killed.](http://stackoverflow.com/a/27521360/2628278)

I recommend you not use it, but I will be glad to review a PR solving this issue

thanks

**Comment by iambmelt** [comment]
@sibeliusseraphini 
>Now I remember about this syntax: Every time someone uses double brace initialisation, a kitten gets killed.

I'm not one to take-sides in programmer dogma but I will say it's valid Java. What you do with that info is your business :)

I won't be submitting a PR w/ a fix only because I was evaluating this library with some sample code before committing to use it in any upcoming project.

**Comment by satyan** [comment]
@iambmelt This initialization creates an anonymous class, for which the tables weren't created. Currently, sugar can only create tables on an initialization step and not on the fly, as would be the case here. 
Also, Sugar depends largely on type/annotation information (to derive table name, etc.), this conflicts on that too.

**Comment by satyan** [comment]
Closing this, as we're not looking to address this case currently.
