### ISSUE TITLE
Tables are not created on version 4.x version of Android, while this works on 5 of Android

### ISSUE THREAD

**Issue by nazeels** [satyan/sugar#513]
Hi All

SugarORM is quiet useful library and thanks you all guys for awesome work.
I have an issue, 
While testing with Android ver. 5.x  library works fine. data storing and retrieving all are working fine

Now later, while i was testing with Android ver 4.x API 18 of Android, the app crashes saying "Unfortunately --app-- has stopped" message. (No exception is thrown)

Reason for the error is no tables are created, in the SQLite database - Sugar.db contains only one table named - "android_metadata" . but required domain tables were not created.

And weird behaviour noticed while debugging is, when I put a breakpoint on the first line to access domain class 
`Product product = Product.first(Product.class); //Which is the first line to use the SugarOrm library and used from OnCreate method of first activity`

If i put a break point at that point, I don't know how but it creates the tables in SQLite.

=========

Can anyone advice how to debug and fix the issue. Following is the logcat error message

`01-31 12:58:32.174 26016-26016/com.wariyum.signage E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: com.wariyum.signage, PID: 26016
                                                                     java.lang.ExceptionInInitializerError
                                                                         at java.lang.Class.classForName(Native Method)
                                                                         at java.lang.Class.forName(Class.java:251)
                                                                         at com.orm.util.ReflectionUtil.getDomainClass(ReflectionUtil.java:270)
                                                                         at com.orm.util.ReflectionUtil.getDomainClasses(ReflectionUtil.java:254)
                                                                         at com.orm.SchemaGenerator.createDatabase(SchemaGenerator.java:37)
                                                                         at com.orm.SugarDb.onCreate(SugarDb.java:26)
                                                                         at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:252)
                                                                         at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:164)
                                                                         at com.orm.SugarDb.getDB(SugarDb.java:36)
                                                                         at com.orm.SugarRecord.find(SugarRecord.java:189)
                                                                         at com.orm.SugarRecord.listAll(SugarRecord.java:94)
                                                                         at com.wariyum.signage.global.Global.getAppSettings(Global.java:54)
                                                                         at com.wariyum.signage.LoginActivity.onCreate(LoginActivity.java:57)
                                                                         at android.app.Activity.performCreate(Activity.java:5280)
                                                                         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1088)
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2322)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2410)
                                                                         at android.app.ActivityThread.access$800(ActivityThread.java:155)
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1331)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:110)
                                                                         at android.os.Looper.loop(Looper.java:193)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5388)
                                                                         at java.lang.reflect.Method.invokeNative(Native Method)
                                                                         at java.lang.reflect.Method.invoke(Method.java:515)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:655)
                                                                         at dalvik.system.NativeStart.main(Native Method)
                                                                      Caused by: java.lang.IllegalStateException: java.lang.NoSuchMethodException: addLikelySubtags [class java.util.Locale]`

**Comment by sibeliusseraphini** [comment]
You can follow this [script](https://gist.github.com/sibeliusseraphini/b060c415604c52c2a94e) to get the tables created by Sugar.
- Make sure your model classes have an empty constructor
- Make sure your Application class extends SugarApp or call SugarContext.init at onCreate of Application

You can always set a breakpoint while debugging in Android Studio, and try to figure it out what is really happening

**Comment by nazeels** [comment]
Thank you for the support :+1: 

- All the models have empty constructors
- And extended the application class with SugarApp and overridden OnCreate with calling method SugarContext.init(this)

The result was the same, do the following screen should give any help

![image](https://cloud.githubusercontent.com/assets/1555473/12703833/ee9d3c0e-c865-11e5-88e9-2227cd0f4f2c.png)

**Comment by sibeliusseraphini** [comment]
The full stack trace should help more.

Put a breakpoint at SugarContext.init as well, and also when Sugar creates the database to check if there is a problem over there

**Comment by jonisaa** [comment]
Show us your meta-data configuration in the androidManifest.xml file.

**Comment by nazeels** [comment]
`<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.wariyum.signage"
    android:versionCode="1"
    android:versionName="1.0">

    <uses-sdk
        android:minSdkVersion="13"
        android:targetSdkVersion="17" />
    
    <meta-data
        android:name="DATABASE"
        android:value="wariyum_signage.db" />
    <meta-data
        android:name="VERSION"
        android:value="1" />
    <meta-data
        android:name="QUERY_LOG"
        android:value="true" />
    <meta-data
        android:name="DOMAIN_PACKAGE_NAME"
        android:value="com.wariyum.signage.domain" />

    
    <uses-permission android:name="android.permission.INTERNET" />

    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"
        android:maxSdkVersion="18" />
    <uses-permission android:name="android.permission.READ_PHONE_STATE" />
    <uses-permission
        android:name="android.permission.READ_EXTERNAL_STORAGE"
        android:maxSdkVersion="18" />
    
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
    
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />

    <application
        android:name="com.orm.SugarApp"
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:theme="@style/AppTheme"

       >
        <activity
            android:name=".LoginActivity"
            android:label="@string/app_name">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        <activity
            android:name=".MainActivity"
            android:label="@string/app_name"
            android:configChanges="orientation|keyboardHidden|screenSize">
        </activity>
        <activity android:name=".ImageZoomActivity"
            android:label="Signage" >
        </activity>

        <service
            android:name=".service.SyncService"
            android:enabled="true"
            android:exported="true" >
        </service>
        <receiver android:name=".service.SyncScheduleReceiver" >
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED" />
            </intent-filter>
        </receiver>
        <receiver android:name=".service.SyncStartServiceReceiver" >
        </receiver>
    </application>
</manifest>
`

**Comment by jonisaa** [comment]
Try this, move all your meta-data tags under the application tag. Then apply a clean project and make it. 

The manifest should be like this:

AndroidManifest.xml

<application android:label="@string/app_name" android:icon="@drawable/icon"
android:name="com.orm.SugarApp">
.
.
<meta-data android:name="DATABASE" android:value="sugar_example.db" />
<meta-data android:name="VERSION" android:value="2" />
<meta-data android:name="QUERY_LOG" android:value="true" />
<meta-data android:name="DOMAIN_PACKAGE_NAME" android:value="com.example" />
.
.
</application>

**Comment by nazeels** [comment]
Yes solved +1

When I properly set the meta-data under application, it is working fine

Thank you for the awesome support @sibeliusseraphini and @jonisaa

**Comment by sutthichai** [comment]
+1

set the meta-data under application tag, it is working!!!

**Comment by rezanahardani** [comment]
**here is resolved...
https://stackoverflow.com/a/44619474/7577642**
