### ISSUE TITLE
Error:Execution failed for task ':app:transformClassesWithDexForDebug

### ISSUE THREAD

**Issue by k0ssi** [satyan/sugar#514]
Still getting error 
````
Error:Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/bin/java'' finished with non-zero exit value 2
```
opened under #511 


Cleaning the caches and "make project" doesn't solve the problem

OSX 10.10.5
Android Studio 1.5.1
JDK 8 U71 (updated this morning)
JRE 8 U71 (updated this morning)


App Settings
CompileSDKVersion 23
buildToolsVersion 22.0.1

dependencies
````
    compile 'com.google.android.gms:play-services:8.4.0'
    compile 'com.android.support:appcompat-v7:23.1.1'
    compile 'com.android.support:support-v4:23.1.1'
    compile 'com.android.support:design:23.1.1'
    compile 'com.squareup.okhttp:okhttp:2.6.0'
    compile 'com.github.satyan:sugar:1.4'
``` 

Is there any possibility to debug the task which failed ? Are there logs somewhere ? 

thanks for helping !

**Comment by sibeliusseraphini** [comment]
It's impossible to debug using just one or two lines of error, you should post more lines of erros.

If you are not afraid of beta, you should use Android 2, it is much better and faster, try to upgrade your dependencies as well

Try to search this error on Google or Stackoverflow, it might help

Try to understand the error message

**Comment by k0ssi** [comment]
after finding out more details by exploring the "gradle console"  i was able to solve the problem
```
:app:transformClassesWithDexForDebug
UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexIndexOverflowException: method ID not in [0, 0xffff]: 65536
	at com.android.dx.merge.DexMerger$6.updateIndex(DexMerger.java:502)
	at com.android.dx.merge.DexMerger$IdMerger.mergeSorted(DexMerger.java:283)
	at com.android.dx.merge.DexMerger.mergeMethodIds(DexMerger.java:491)
	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:168)
	at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
	at com.android.dx.command.dexer.Main.run(Main.java:246)
	at com.android.dx.command.dexer.Main.main(Main.java:215)
	at com.android.dx.command.Main.main(Main.java:106)



 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/bin/java'' finished with non-zero exit value 2
```

```
com.android.dex.DexIndexOverflowException: method ID not in [0, 0xffff]: 65536
```
means i have reached to default limitation of 65k methods within one app.

So i had to enable multidex,which solves the problem. 

Got more information here http://developer.android.com/tools/building/multidex.html
