### ISSUE TITLE
NoClassDefFoundError - API 21

### ISSUE THREAD

**Issue by enyciaa** [satyan/sugar#517]
Hi,

I'm getting the crash below, but only on devices running API 21. I'm not sure what other information you may need? But let me know and I'll post it here.

I'm running Sugar 1.4
and use build tools 23.0.1

> java.lang.NoClassDefFoundError: com.boundless.cbt.workouts.TDPageOneFragment$3
                                                                       at java.lang.Class.classForName(Native Method)
                                                                       at java.lang.Class.forName(Class.java:308)
                                                                       at com.orm.util.ReflectionUtil.getDomainClass(ReflectionUtil.java:270)
                                                                       at com.orm.util.ReflectionUtil.getDomainClasses(ReflectionUtil.java:254)
                                                                       at com.orm.SchemaGenerator.createDatabase(SchemaGenerator.java:37)
                                                                       at com.orm.SugarDb.onCreate(SugarDb.java:26)
                                                                       at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:251)
                                                                       at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
                                                                       at com.orm.SugarDb.getDB(SugarDb.java:36)
                                                                       at com.orm.SugarRecord.count(SugarRecord.java:218)
                                                                       at com.orm.SugarRecord.count(SugarRecord.java:209)
                                                                       at com.boundless.cbt.workouts.TDActivity.loadLastDiaryEntry(TDActivity.java:559)
                                                                       at com.boundless.cbt.workouts.TDActivity.onResume(TDActivity.java:135)
                                                                       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1241)
                                                                       at android.app.Activity.performResume(Activity.java:6019)
                                                                       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2940)
                                                                       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2982)
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2365)
                                                                       at android.app.ActivityThread.access$800(ActivityThread.java:144)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                       at android.os.Looper.loop(Looper.java:135)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5221)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

**Comment by jonisaa** [comment]
Could you post your AndroidManifest file? 
Did you generate default constructor for all your domain classes?

**Comment by enyciaa** [comment]
`

        <meta-data android:name="DATABASE" android:value="moodspace_sugarorm.db" />
        <meta-data android:name="VERSION" android:value="1" />
        <meta-data android:name="QUERY_LOG" android:value="true" />
        <meta-data android:name="DOMAIN_PACKAGE_NAME" android:value="com.boundless.cbt.workouts" />`

I think that's the bit in the manifest you're looking for? 
Also I'm not sure what you mean by domain classes?

**Comment by jonisaa** [comment]
Yes! That's what I looking for! Did you put the meta-data tags under the application tag? I strong recommend you to put value "2" in VERSION meta-data. 

For domain classes I refer to those who are part of your database model. The classes you got under the package com.boundless.cbt.workouts. Take a look at this classes and verify if they got an empty constructor.

**Comment by enyciaa** [comment]
Yep they're under the application tag. And I tried making the version number as 2 - still crashes. 

Here's my domain class:

`@Table
public class TDDiaryEntryModel extends SugarRecord implements Serializable {

    @Ignore
    public static final String TYPE_USER_ENTERED = "user_entered";

    @Ignore
    public static final String TYPE_HINT = "hint";

    @Ignore
    public static final String TYPE_EXAMPLE = "example";

    @Ignore
    // Indicates the model type
    public String type = TYPE_HINT;

    public String date;

    public String title;

    public String situation;

    public String auto_thoughts;

    public String emotions;

    // Delimited string of distortion ids
    public String cognitive_distortion_ids;

    public String alt_thoughts;

    public String outcome;

    public int distress_rating_one;

    public int distress_rating_two;


    /**
     * Constructor
     */
    public TDDiaryEntryModel() {
    }


    /**
     * Get cognitive distortion ids
     */
    public String[] getDistortionIds() {
        String string = cognitive_distortion_ids;

        if (string == null) {
            return null;
        }
        else {
            String[] mIds = string.split("\\|");
            String[] trimmedArray = new String[mIds.length];
            for (int i = 0; i < mIds.length; i++)
                trimmedArray[i] = mIds[i].trim();

            return trimmedArray;
        }
    }


    /**
     * Set cognitive distortion ids
     */
    public void setDistortionIds(String[] distortion_ids) {
        if (distortion_ids == null) {
            cognitive_distortion_ids = null;
        }
        else if (distortion_ids.length == 0) {
            cognitive_distortion_ids = null;
        }
        else {
            StringBuilder sb = new StringBuilder();
            for (String id : distortion_ids) {
                sb.append(id.trim());
                sb.append("|");
            }
            cognitive_distortion_ids = sb.toString();
        }
    }

}
`

**Comment by jonisaa** [comment]
If your Model class extends SugarRecord there is no need to include the @Table annotation. And another thing I would recommend to you, in Android avoid using the Serializable interface. Use a Parcelator, take a look at http://parceler.org/

**Comment by enyciaa** [comment]
Thanks that looks good! I always avoided parceling because of the extra boiler plate code.

That method does some actions on the database using the sugarDb.count and sugarDb.last methods. I tried commenting out the whole method and just using save() on a dummy entity, but the same crash occurs.

**Comment by enyciaa** [comment]
Found a work around!

As long as one of the sugar methods is called on the domain class BEFORE starting TDActivity the database is created and there is no crash thereafter.

As to why, and why only on Lollipop - better minds than mine may be able to figure it out ;)
I tried recreating the bug in a fresh project that copied my setup with no luck
