### ISSUE TITLE
Crash on prelollipop devices

### ISSUE THREAD

**Issue by nomanr** [satyan/sugar#525]
The app is working fine on lollipop devices, but somehow sugar is causing the crash on prelollipop devices. Heres the log
```
 java.lang.NoClassDefFoundError: com.orm.util.ManifestHelper
                                                                         at com.orm.SugarDb.<init>(SugarDb.java:19)
                                                                         at com.orm.SugarContext.<init>(SugarContext.java:18)
                                                                         at com.orm.SugarContext.init(SugarContext.java:30)
                                                                         at com.tagbond.model.Global2.onCreate(App.java:58)
                                                                         at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
                                                                         at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4328)
                                                                         at android.app.ActivityThread.access$1500(ActivityThread.java:135)
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                         at android.os.Looper.loop(Looper.java:136)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                                         at java.lang.reflect.Method.invokeNative(Native Method)
                                                                         at java.lang.reflect.Method.invoke(Method.java:515)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                                         at dalvik.system.NativeStart.main(Native Method)
```

**Comment by ALJazeeraIDP** [comment]
I have the same problem..

`02-17 11:22:32.141 25391-25391/com.aj.imtiyazat E/AndroidRuntime: FATAL EXCEPTION: main
                                                                  java.lang.NoClassDefFoundError: com.orm.util.ManifestHelper
                                                                      at com.orm.SugarDb.<init>(SugarDb.java:19)
                                                                      at com.orm.SugarContext.<init>(SugarContext.java:18)
                                                                      at com.orm.SugarContext.init(SugarContext.java:30)
                                                                      at com.orm.SugarApp.onCreate(SugarApp.java:12)
                                                                      at com.aj.imtiyazat.ImtiyazatApplication.onCreate(ImtiyazatApplication.java:15)
                                                                      at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1017)
                                                                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4590)
                                                                      at android.app.ActivityThread.access$1400(ActivityThread.java:157)
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                      at android.os.Looper.loop(Looper.java:176)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5317)
                                                                      at java.lang.reflect.Method.invokeNative(Native Method)
                                                                      at java.lang.reflect.Method.invoke(Method.java:511)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
                                                                      at dalvik.system.NativeStart.main(Native Method)
02-17 11:22:32.231 25391-25413/com.aj.imtiyazat E/GMPM: Uploading is not possible. App measurement disabled`

**Comment by ALJazeeraIDP** [comment]
I fixed it.. You need to enable multidex and library for below lollipop devices.. Please follow the link: http://developer.android.com/tools/building/multidex.html 
and 
http://stackoverflow.com/a/28722345/908874
