### ISSUE TITLE
Table is not empty, but I've got NPE

### ISSUE THREAD

**Issue by burnix** [satyan/sugar#528]
I fill my DB with strings and integers

  for (int i = 0; i < 35; i++) {
            System.out.println(getResources().getStringArray(R.array.questions)[i]);
            questionery = new Question(getResources().getStringArray(R.array.questions)[i], i);
            questionery.save();
        }

but  when I tried to get one of them  I crashed with NPE

Question q = Question.findById(Question.class, 33);  <<<<- q is null
String text = q.getText()      <<<-------- NPE

**Comment by jonisaa** [comment]
The table is correctly created?

**Comment by jonisaa** [comment]
@burnix please, show me your Question class code

**Comment by jonisaa** [comment]
@burnix try this: 

```java
for (int i = 0; i < 35; i++) {
    //This is not correct: System.out.println(getResources().getStringArray(R.array.questions)[i]);
    Log.d("some_tag", getResources().getStringArray(R.array.questions)[i])
    questionery = new Question(getResources().getStringArray(R.array.questions)[i], i);
    //Replace this: questionery.save(); 
    Question.save(questionery);
}
```

**Comment by burnix** [comment]
public class Question extends SugarRecord {
    private String question;
    private int number;

    public Question(String question, int number) {
        this.question = question;
        this.number = number;
    }

    public String getQuestion() {
        return question;
    }

**Comment by burnix** [comment]
@jonisaa ,
I'm  checking if table  is filled:
long x = Question.count(Question.class);
and  x=35

And  you advise  `Question.save(questionery);` didn't  help, unfortunately :(

**Comment by burnix** [comment]
@jonisaa 
Thus, when I tried to `List<Question> list =  Question.listAll(Question.class);` I've got `java.lang.IndexOutOfBoundsException`. 
So  the  `count`  is  35, but I still  can't use none of them...

**Comment by jonisaa** [comment]
@burnix please, show me the entire stacktrace of the error!

**Comment by burnix** [comment]
@jonisaa , sure
02-22 14:44:11.989 8465-8465/com.ainura.orm E/AndroidRuntime: FATAL EXCEPTION: main
                                                              Process: com.ainura.orm, PID: 8465
                                                              java.lang.NullPointerException
                                                                  at com.ainura.orm.MainActivity$1.onClick(MainActivity.java:43)
                                                                  at android.view.View.performClick(View.java:4456)
                                                                  at android.view.View$PerformClick.run(View.java:18462)
                                                                  at android.os.Handler.handleCallback(Handler.java:733)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                  at android.os.Looper.loop(Looper.java:136)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5102)
                                                                  at java.lang.reflect.Method.invokeNative(Native Method)
                                                                  at java.lang.reflect.Method.invoke(Method.java:515)
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                                  at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
                                                                  at dalvik.system.NativeStart.main(Native Method)

**Comment by burnix** [comment]
@jonisaa in this  line `String q = questionery.getQuestion();`  (`cos questionery is null)

**Comment by jonisaa** [comment]
Your Question class needs an Empty constructor, add an empty constructor, then a gradle clean build, and run it. 

The class should be like this:

```java
public class Question extends SugarRecord {
   private String question; 
   private int number;

   public Question() { }

   public Question(String question, int number) {
       this.question = question;
       this.number = number;
   }

   public String getQuestion() {
       return question;
   }
```

**Comment by burnix** [comment]
@jonisaa thank you very much. The deal was really in empty constructor. May be  you can  give a little  explanation why do we need it here?

**Comment by jonisaa** [comment]
@burnix Okey, I will give you a little explanation. SugarORM uses reflection and annotation processing to generate the tables. That's why it's needed an empty constructor.

**Comment by sibeliusseraphini** [comment]
Here is one line of code that requires an empty constructor: https://github.com/satyan/sugar/blob/master/library/src/main/java/com/orm/SugarRecord.java#L212
