### ISSUE TITLE
Could not find class 'com.google.common.collect.MapMaker', referenced from method com.orm.SugarContext.<init>

### ISSUE THREAD

**Issue by jiangbing9293** [satyan/sugar#543]
03-15 21:12:30.595 20427-20427/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   java.lang.NoClassDefFoundError: com.google.common.collect.MapMaker
                                                       at com.orm.SugarContext.<init>(SugarContext.java:19)
                                                       at com.orm.SugarContext.init(SugarContext.java:30)
                                                       at com.freelancer.netviomsafepus.MainActivity.onCreate(MainActivity.java:15)
                                                       at android.app.Activity.performCreate(Activity.java:5104)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2144)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230)
                                                       at android.app.ActivityThread.access$600(ActivityThread.java:141)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
                                                       at android.os.Handler.dispatchMessage(Handler.java:99)
                                                       at android.os.Looper.loop(Looper.java:137)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5041)
                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:511)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:817)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:584)
                                                       at dalvik.system.NativeStart.main(Native Method)

**Comment by sibeliusseraphini** [comment]
this is fixed on master and on Sugar 1.5

**Comment by jiangbing9293** [comment]
ok, got it ,thank you!
