### ISSUE TITLE
Saving Data

### ISSUE THREAD

**Issue by Gujarats** [satyan/sugar#545]
When I tried to save the data using this libary I got this error showing up in my logcat : 

```
03-16 18:48:20.322 10610-10610/com.buddiesnation.buddiesnation W/nalizableReferenceQueue: Could not load Finalizer in its own class loader.Loading Finalizer in the current class loader instead. As a result, you will not be ableto garbage collect this class loader. To support reclaiming this class loader, eitherresolve the underlying issue, or move Google Collections to your system class path.
                                                                                          java.io.FileNotFoundException: com/google/common/base/internal/Finalizer.class
                                                                                              at com.google.common.base.FinalizableReferenceQueue$DecoupledLoader.getBaseUrl(FinalizableReferenceQueue.java:311)
                                                                                              at com.google.common.base.FinalizableReferenceQueue$DecoupledLoader.loadFinalizer(FinalizableReferenceQueue.java:295)
                                                                                              at com.google.common.base.FinalizableReferenceQueue.loadFinalizer(FinalizableReferenceQueue.java:214)
                                                                                              at com.google.common.base.FinalizableReferenceQueue.<clinit>(FinalizableReferenceQueue.java:138)
                                                                                              at java.lang.Class.classForName(Native Method)
                                                                                              at java.lang.Class.forName(Class.java:308)
                                                                                              at com.orm.util.ReflectionUtil.getDomainClass(ReflectionUtil.java:270)
                                                                                              at com.orm.util.ReflectionUtil.getDomainClasses(ReflectionUtil.java:254)
                                                                                              at com.orm.SchemaGenerator.createDatabase(SchemaGenerator.java:37)
                                                                                              at com.orm.SugarDb.onCreate(SugarDb.java:26)
                                                                                              at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:251)
                                                                                              at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
                                                                                              at com.orm.SugarDb.getDB(SugarDb.java:36)
                                                                                              at com.orm.SugarRecord.save(SugarRecord.java:360)
                                                                                              at com.friendlyst.friendlyst.PostLoginActivity.Services.ServicesAddActivity$1.apiResponseSuccess(ServicesAddActivity.java:95)
                                                                                              at Controllers.API.processCreatePostService(API.java:1133)
                                                                                              at Controllers.API.requestDidFinish(API.java:1001)
                                                                                              at HBURLConnection.HBUrlConnection$OverlayTask.onPostExecute(HBUrlConnection.java:293)
                                                                                              at HBURLConnection.HBUrlConnection$OverlayTask.onPostExecute(HBUrlConnection.java:261)
                                                                                              at android.os.AsyncTask.finish(AsyncTask.java:632)
                                                                                              at android.os.AsyncTask.access$600(AsyncTask.java:177)
                                                                                              at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
                                                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                              at android.os.Looper.loop(Looper.java:135)
                                                                                              at android.app.ActivityThread.main(ActivityThread.java:5221)
                                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                                              at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
                                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
03-16 18:48:20.323 10610-10610/com.buddiesnation.buddiesnation I/Finalizer: Couldn't access Thread.inheritableThreadLocals. Reference finalizer threads will inherit thread local values.
03-16 18:48:20.880 10610-10620/com.buddiesnation.buddiesnation W/art: Suspending all threads took: 19.947ms
03-16 18:48:20.884 10610-10625/com.buddiesnation.buddiesnation I/art: Background partial concurrent mark sweep GC freed 94446(3MB) AllocSpace objects, 0(0B) LOS objects, 30% free, 35MB/51MB, paused 1.675ms total 150.587ms
03-16 18:48:21.039 10610-10610/com.buddiesnation.buddiesnation I/Sugar: Create table
03-16 18:48:21.040 10610-10610/com.buddiesnation.buddiesnation D/Sugar: Fetching properties
03-16 18:48:21.040 10610-10610/com.buddiesnation.buddiesnation I/Sugar: Creating table M_SERVICES_TABLE
03-16 18:48:21.059 10610-10610/com.buddiesnation.buddiesnation I/Sugar: MServicesTable saved : 1
03-16 18:48:21.063 10610-10610/com.buddiesnation.buddiesnation I/Choreographer: Skipped 134 frames!  The application may be doing too much work on its main thread.

```

I think from the logcat I'm sure the table and the the data that I want to save is inserted, and I just curious about this message : _Could not load Finalizer in its own class loader.Loading Finalizer in the current class loader instead. As a result, you will not be ableto garbage collect this class loader. To support reclaiming this class loader, eitherresolve the underlying issue, or move Google Collections to your system class path_. What does it mean?

**Comment by JonatanSalas** [comment]
@Gujarats are you using Roboguice? I found an stackoverflow post about this error http://stackoverflow.com/questions/16718082/java-io-filenotfoundexception-com-google-inject-internal-util-finalizer-class. It's not related to sugar, so I will close it. If you need more help with this, please re open and I will try to help you!

**Comment by Gujarats** [comment]
No I'm not using Roboguice, I got that log error when using older sugar version, when updating it to 1.5 the error is gone, I thought it was sugar problem, I'm not sure my self. Thanks @JonatanSalas .

**Comment by marconealberto** [comment]
this happens to me with 1.5 if I put Sugar inside a background task.

```
  @Override
    protected Void doInBackground(String... params) {
        List<User> listResponse = SugarRecord.listAll(User.class);
```
