### ISSUE TITLE
sugarorm can't work for android 5.0+

### ISSUE THREAD

**Issue by JackLauu** [satyan/sugar#573]
When I use SugarOrm in android 5.0+, it give a no such table exception report, android 4.x works well. If sugar can't create tables in android 5.0+ automatically? And there is no way for check table is exist. I have update the library to 1.5, I use android studio 2.0 with maven.

**Comment by JonatanSalas** [comment]
@JackLauu can you give more information about the error? Could you show me the entire stack trace?

**Comment by JackLauu** [comment]
Caused by: android.database.sqlite.SQLiteException: no such table: BOOKMARK (code 1): , while compiling: SELECT * FROM BOOKMARK WHERE BOOK_ID = ?
                                                                                           at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
                                                                                           at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
                                                                                           at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
                                                                                           at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
                                                                                           at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
                                                                                           at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
                                                                                           at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
                                                                                           at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1316)
                                                                                           at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1163)
                                                                                           at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1034)
                                                                                           at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1240)
                                                                                           at com.orm.SugarRecord.find(SugarRecord.java:201)
                                                                                           at com.orm.SugarRecord.find(SugarRecord.java:187)
                                                                                           at org.godfootsteps.thechurchofalmightygod.adapter.BookmarkRecycleAdapter.<init>(BookmarkRecycleAdapter.java:37)

 public BookmarkRecycleAdapter() {
        this.bookmarks = Bookmark.find(Bookmark.class, "BOOK_ID = ?", bookId);
    }

Thank you for you reply, stack trace is below.

**Comment by JonatanSalas** [comment]
The tables are generated correctly when you deploy for first time your app? How did you put the configuration in the AndroidManifest.xml? All of your domain classes provides an Empty constructor?

**Comment by JackLauu** [comment]
Thank you JonatanSalas, I think my problem is the same as issue #575.

**Comment by JonatanSalas** [comment]
OK! I will close the issue, if you still have this trouble please re open it!
