### ISSUE TITLE
SQLiteDiskIOException: disk I/O error

### ISSUE THREAD

**Issue by LvWind** [satyan/sugar#583]
Samsumg i9082 Android 4.2.2
Sugar version: b16e65326a(i've got same error in v1.5)
log here:
```
android.database.sqlite.SQLiteDiskIOException: disk I/O error (code 1802)
	at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(SQLiteConnection.java)
	at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:973)
	at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
	at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
	at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1591)
	at com.orm.SugarRecord.save(SugarRecord.java:285)
	at com.orm.SugarRecord.save(SugarRecord.java:423)
	at com.*.DbUtil.reorderBookmark(DbUtil.java:34)
```
code here:
```java
public static void reorderBookmark() {
        List<Bookmark> bookmarkList = new ArrayList<>();
        bookmarkList = SugarRecord.listAll(Bookmark.class,"POSITION");

        for (int i = 0; i < bookmarkList.size(); i++) {
            Bookmark bookmark = Bookmark.findById(Bookmark.class, bookmarkList.get(i).getId());
            bookmark.setPosition(i);
            bookmark.save();
        }
    }
```

and there is another SQLiteDiskIOException
```
Caused by: android.database.sqlite.SQLiteDiskIOException: disk I/O error (code 778)
	at android.database.sqlite.SQLiteConnection.nativeExecute(SQLiteConnection.java)
	at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:741)
	at android.database.sqlite.SQLiteSession.endTransactionUnchecked(SQLiteSession.java:437)
	at android.database.sqlite.SQLiteSession.endTransaction(SQLiteSession.java:401)
	at android.database.sqlite.SQLiteDatabase.endTransaction(SQLiteDatabase.java:524)
	at com.orm.SugarRecord.saveInTx(SugarRecord.java:71)
```

**Comment by JonatanSalas** [comment]
@LvWind this could be a problem of storage capacity in your mobile phone.

**Comment by LvWind** [comment]
But I've got plenty of crash log in my issue tracker recently from all kinds of devices.

**Comment by LvWind** [comment]
And all of them are Samsumg devices

**Comment by JonatanSalas** [comment]
There is a post in stackoverflow that explains this.. You are performing this code from the Main UI thead? http://stackoverflow.com/questions/21554277/android-sqlite-database-sqlitediskioexception-disk-i-o-error-code-1802

**Comment by JonatanSalas** [comment]
There is also another post explaining the code 778 error http://stackoverflow.com/questions/14226377/what-can-cause-sqlite-error-code-778-on-android

**Comment by LvWind** [comment]
oh! confirmed its bug of 4.4.2.
thank you.

**Comment by JonatanSalas** [comment]
You are welcome!
