### ISSUE TITLE
sugar save()

### ISSUE THREAD

**Issue by songsh** [satyan/sugar#591]
save() have no returned value, how i know save result ,yes or no?

**Comment by JonatanSalas** [comment]
Are you using SugarRecord.save() or instance method save() inherited from sugar record?

**Comment by songsh** [comment]
method save() inherited from sugar record

**Comment by songsh** [comment]
android.database.sqlite.SQLiteDiskIOException: disk I/O error (code 778)
		at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
		at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:927)
		at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:754)
		at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64)
		at android.database.sqlite.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.java:1696)
		at android.database.sqlite.SQLiteDatabase.update(SQLiteDatabase.java:1642)
		at com.blueware.agent.android.instrumentation.SQLiteInstrumentation.update(SQLiteInstrumentation.java)
		at com.orm.SugarRecord.save(SugarRecord.java:128)
		at com.orm.SugarRecord.save(SugarRecord.java:45)

**Comment by JakeSteam** [comment]
Sugar will always save. It uses insert or update, so `save()` will always be successful.
