### ISSUE TITLE
Sugar first startup

### ISSUE THREAD

**Issue by lumueller** [satyan/sugar#598]
Hi,
every time I reinstall my app and sugar is called for the first time (e.g. object.save()) got these error:

```
 W/nalizableReferenceQueue: Could not load Finalizer in its own class loader.Loading Finalizer in the current class loader instead. As a result, you will not be ableto garbage collect this class loader. To support reclaiming this class loader, eitherresolve the underlying issue, or move Google Collections to your system class path.
java.io.FileNotFoundException: com/google/common/base/internal/Finalizer.class
    at com.google.common.base.FinalizableReferenceQueue$DecoupledLoader.getBaseUrl(FinalizableReferenceQueue.java:251)
    at com.google.common.base.FinalizableReferenceQueue$DecoupledLoader.loadFinalizer(FinalizableReferenceQueue.java:235)
    at com.google.common.base.FinalizableReferenceQueue.loadFinalizer(FinalizableReferenceQueue.java:157)
    at com.google.common.base.FinalizableReferenceQueue.<clinit>(FinalizableReferenceQueue.java:86)
    at java.lang.Class.classForName(Native Method)
    at java.lang.Class.forName(Class.java:401)
    at com.orm.util.ReflectionUtil.getDomainClass(ReflectionUtil.java:274)
    at com.orm.util.ReflectionUtil.getDomainClasses(ReflectionUtil.java:258)
    at com.orm.SchemaGenerator.createDatabase(SchemaGenerator.java:45)
    at com.orm.SugarDb.onCreate(SugarDb.java:28)
    at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:251)
    at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
    at com.orm.SugarDb.getDB(SugarDb.java:38)
    at com.orm.SugarRecord.getSugarDataBase(SugarRecord.java:35)
    at com.orm.SugarRecord.save(SugarRecord.java:416)
    ...
```
    
This error takes about 3-5 seconds and then my tables are created.

I am using v1.5., got this right now in a Nexus5 and Nexus6.

I searched the issues and found this https://github.com/satyan/sugar/issues/545 ... i do not use roboguice either and changing to 1.5. did not help.

**Comment by richdyang** [comment]
+1

**Comment by leof23** [comment]
I have this problem too, anyone found the solution?
