### ISSUE TITLE
Create all tables at first time run app

### ISSUE THREAD

**Issue by kenk11** [satyan/sugar#607]
Hi guys,
I have service query all tables anytime so I want to create all table without data
I tried migrate for create all tables but it's not worked!
Can you show me how to create all table or give me another solution!
Thanks!

**Comment by JonatanSalas** [comment]
Could you specify a little bit better your trouble?

**Comment by kenk11** [comment]
I have a service run background, it will scan all table and upload data to server
So the first time app runs, no table no data, it's error "no such table" and i want to creat empty table just have table name and column

**Comment by larrytech7** [comment]
What do you mean first time? The first time your persistent object runs, Sugar creates the corresponding table for your object and it is empty if you haven't yet set data on your object to persist. Your class just needs the fields as column names which sugar formats a little differently depending on how you name them.

**Comment by kenk11** [comment]
I mean first time is when user install then run it.
And I want to check table exist or not, 
Another way, i want to create empty table if dont have method check table exist

**Comment by larrytech7** [comment]
you can check if the table exists or not by just querying for the data. When you get an empty list, then it means empty. Table creation is done automatically so you don't have to worry about the daunting tasks of table management. Else you might want to implement your own content providers and databases yourself, which is really not what you want to do having this library around.

**Comment by kenk11** [comment]
But the first time check when dont have table and data, it crash with error "no such table" so i want to by pass error

Any idea for solution?

**Comment by larrytech7** [comment]
OOH, i see what you mean. This usually happens when you don't set the meta-data for the database config parameters in you Manifest file as part of the application meta data. What way do you use the ORM, @Table annotation or extend the SugarRecord class? Do you have the following SET in your manifest? 

<meta-data android:name="DATABASE" android:value="sugar_example.db" />
<meta-data android:name="VERSION" android:value="2" />
<meta-data android:name="QUERY_LOG" android:value="true" />
<meta-data android:name="DOMAIN_PACKAGE_NAME" android:value="com.example" />

These are all optional but it looks like it does crash when missing with version 1.4 or so.

**Comment by kenk11** [comment]
I configured
`
  
        <meta-data
            android:name="DATABASE"
            android:value="TripMaester.db"/>
        <meta-data
            android:name="VERSION"
            android:value="10"/>
        <meta-data
            android:name="QUERY_LOG"
            android:value="true"/>
        <meta-data
            android:name="DOMAIN_PACKAGE_NAME"
            android:value="vn.edu.hcmut.traffic.tripmaester"/>
        
`
and Im using version 1.5 but still error

**Comment by larrytech7** [comment]
can you paste the exact error you are getting ?

**Comment by kenk11** [comment]
Here they are
`
FATAL EXCEPTION: IntentService[UploadService]
                                                                                  Process: vn.edu.hcmut.traffic.tripmaester, PID: 19053
                                                                                  android.database.sqlite.SQLiteException: no such table: TRIP_DETAIL (code 1): , while compiling: SELECT * FROM TRIP_DETAIL WHERE (M_STATUS = ? )
                                                                                      at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
                                                                                      at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
                                                                                      at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
                                                                                      at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
                                                                                      at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
                                                                                      at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
                                                                                      at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
                                                                                      at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1316)
                                                                                      at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1163)
                                                                                      at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1034)
                                                                                      at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1240)
                                                                                      at com.orm.SugarRecord.find(SugarRecord.java:201)
                                                                                      at com.orm.query.Select.list(Select.java:138)
                                                                                      at vn.edu.hcmut.traffic.tripmaester.store.db.TripDetail.getListTripStatus(TripDetail.java:90)
                                                                                      at vn.edu.hcmut.traffic.tripmaester.service.http.UploadService.onHandleIntent(UploadService.java:30)
                                                                                      at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                      at android.os.Looper.loop(Looper.java:135)
                                                                                      at android.os.HandlerThread.run(HandlerThread.java:61)
`

And here is TripDetail.java:90
`
ArrayList<TripDetail> listTripDetail = (ArrayList<TripDetail>) Select.from(TripDetail.class)
                .where(Condition.prop("M_STATUS").eq(status))
                .list();
`

**Comment by larrytech7** [comment]
Try changing the version of your DB (increment it). Also turn off instant run if you have that setup for versions of studio >= 2.0

**Comment by kenk11** [comment]
OMG, it worked when i disable instant run
Thanks @larrytech7 
Can you explain why we have to disable instant run?

**Comment by larrytech7** [comment]
It seems that instant run doesn't take into consideration changes at certain levels like in the manifest. So one always has to build the entire code for changes to take effect. Hopefully it would get fixed with later versions of studio. Checkout 2.2+ of studio or so.

**Comment by larrytech7** [comment]
i think you can now close this issue.
Thanks
