### ISSUE TITLE
Upgrade from 1.3

### ISSUE THREAD

**Issue by mesterj** [satyan/sugar#615]
Hello
I have an app. Which used 1.3 (db version 1) . There was an update with 1.4 (db version 2) . And a brand new version with 1.5 (db version 3). 
If I upgrade 1.3 -> 1.4 -> 1.5 everything is good. 

In this way there is 2.sql file in asset/sugar_upgrades. I saw  in logcat the alter table commands are commited.

If I upgrade 1.3 -> 1.5 there are some errors and whole db is deleted on the device.
Errors:

05-31 11:30:34.201 29140-29140/? W/System.err:     at com.orm.SchemaGenerator.executeSugarUpgrade(SchemaGenerator.java:100)
05-31 11:30:34.201 29140-29140/? W/System.err:     at com.orm.SugarDb.onUpgrade(SugarDb.java:33)
05-31 11:30:34.201 29140-29140/? W/System.err:     at com.orm.SugarDb.getDB(SugarDb.java:38)
05-31 11:30:34.201 29140-29140/? W/System.err:     at com.orm.SugarRecord.getSugarDataBase(SugarRecord.java:35)
05-31 11:30:34.201 29140-29140/? W/System.err:     at com.orm.SugarRecord.count(SugarRecord.java:238)
05-31 11:30:34.201 29140-29140/? W/System.err:     at com.orm.SugarRecord.count(SugarRecord.java:226)

**Comment by larrytech7** [comment]
When you first run the database, and later upgrade, you have to export your data and remove all the previous data on the device and uninstall. Then install now your app and it should run with the recent version of your database.
