### ISSUE TITLE
Cursor error when using findWithQuery

### ISSUE THREAD

**Issue by cherry-wave** [satyan/sugar#616]
Hi,

first I want to say SugarORM is pure sugar ;) I really love it!

But! D= I wanted to use findWithQuery to receive a List of entries where the boolean active = true. I took a look at the database and found out you save booleans as 0/1. So my query looks like this:

SELECT characters FROM SYLLABLE WHERE active = 1

and set arguments to null. When I execute it, following error occurs and 0 items are returned:

```
05-31 20:16:56.398 4013-4013/cherry_wave.nmg E/CursorWindow: Failed to read row 0, column -1 from a CursorWindow which has 2 rows, 1 columns.
05-31 20:16:56.399 4013-4013/cherry_wave.nmg W/System.err: java.lang.IllegalStateException: Couldn't read row 0, col -1 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
05-31 20:16:56.400 4013-4013/cherry_wave.nmg W/System.err:     at android.database.CursorWindow.nativeGetLong(Native Method)
05-31 20:16:56.400 4013-4013/cherry_wave.nmg W/System.err:     at android.database.CursorWindow.getLong(CursorWindow.java:511)
05-31 20:16:56.400 4013-4013/cherry_wave.nmg W/System.err:     at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:75)
05-31 20:16:56.400 4013-4013/cherry_wave.nmg W/System.err:     at com.orm.SugarRecord.inflate(SugarRecord.java:354)
05-31 20:16:56.400 4013-4013/cherry_wave.nmg W/System.err:     at com.orm.SugarRecord.getEntitiesFromCursor(SugarRecord.java:213)
05-31 20:16:56.400 4013-4013/cherry_wave.nmg W/System.err:     at com.orm.SugarRecord.findWithQuery(SugarRecord.java:193)
```

Am I missing on something?

**Comment by cherry-wave** [comment]
OK, forget it, of course it should be SELECT * FROM =D

**Comment by emashara** [comment]
can u tell me how u fixed this error @cherry-wave
