### ISSUE TITLE
Instrumentation Testing : SQLiteException: no such table

### ISSUE THREAD

**Issue by sandeep-loktra** [satyan/sugar#625]
While executing for instrumentation testing ends up with an error

```
Testing started at 5:24 PM ...

06/16 17:24:16: Launching ApplicationTest
No apk changes detected since last installation, skipping installation of /Users/sandeeprana/StudioProjects/iliad_agent/app/build/outputs/apk/app-debug.apk
$ adb shell am force-stop com.loktra.iliadagent
$ adb push /Users/sandeeprana/StudioProjects/iliad_agent/app/build/outputs/apk/app-debug-androidTest-unaligned.apk /data/local/tmp/com.loktra.iliadagent.test
$ adb shell pm install -r "/data/local/tmp/com.loktra.iliadagent.test"
	pkg: /data/local/tmp/com.loktra.iliadagent.test
Success


Running tests

$ adb shell am instrument -w -r   -e debug false -e class com.loktra.iliadagent.ApplicationTest com.loktra.iliadagent.test/com.android.test.runner.MultiDexTestRunner
Client not ready yet..Test running started

android.database.sqlite.SQLiteException: no such table: MY_GROUPS_TABLE (code 1): , while compiling: INSERT OR REPLACE  INTO MY_GROUPS_TABLE(GROUPNAME,GROUPAVATAR,ID,GROUPDESCRIPTION,GROUPID) VALUES (?,?,?,?,?)
at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:891)
at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:502)
at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1469)
at com.orm.SugarRecord.save(SugarRecord.java:266)
at com.orm.SugarRecord.save(SugarRecord.java:246)
at com.loktra.iliadagent.ApplicationTest.testDatabase(ApplicationTest.java:47)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:191)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:176)
at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:555)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1853)

Tests ran to completion.


```

Here is my class Code

package com.loktra.iliadagent;

```
public class ApplicationTest extends ApplicationTestCase<Application> {
    static final String DB_NAME = "iliad.db";

    public ApplicationTest() {
        super(Application.class);
    }


    @Override
    protected void setUp() throws Exception {
        super.setUp();
        boolean deleted = mContext.deleteDatabase(DB_NAME);

        SugarContext.init(mContext);
        SugarConfig.clearCache();

    }

    /**
     * Check if tables created or not
     */
    public void testDatabase() {

        int currentapiVersion = android.os.Build.VERSION.SDK_INT;
        if (currentapiVersion >= android.os.Build.VERSION_CODES.LOLLIPOP) {
            long mgId = MyGroupsTable.save(new MyGroupsTable());
            MyGroupsTable myGroupsTable = MyGroupsTable.findById(MyGroupsTable.class, mgId);
            long rows = myGroupsTable.count(MyGroupsTable.class);
            MyGroupsTable.delete(myGroupsTable);

            assertTrue("Failed check table", rows > 0);
        } else {
            MyGroupsTable.findById(MyGroupsTable.class, (long) 1);
            long j = MyGroupsTable.save(new MyGroupsTable("1", "testing", "description", "avatar"));
            assertTrue("Failed to create table", j < 0);
            List<MyGroupsTable> my = MyGroupsTable.find(MyGroupsTable.class, " GROUPID = ?", "1");
            if (my.size() > 0) {
                assertTrue(true);
            } else {
                assertTrue(false);
            }

            assertTrue("Failed to get results from MyGroupsTable", my.get(0).getGroup_id().equals("1"));
        }
    }

}
```

It is working perfectly while running as debug/release.
NOTE: Instant run is disabled.

**Comment by gelandesprung** [comment]
it works on android 4.0 4.2 4.4

**Comment by vulpeszerda** [comment]
same here
