### ISSUE TITLE
java.lang.NoClassDefFoundError: com.orm.util.ContextUtil

### ISSUE THREAD

**Issue by kmno** [satyan/sugar#631]
Hi, I'm using master version at my project based on tutorial. but when i test on kitkat devices i get this error:

E/AndroidRuntime: FATAL EXCEPTION: main
                                                           Process: ir.winwin, PID: 21184
                                                           java.lang.NoClassDefFoundError: com.orm.util.ContextUtil
                                                               at com.orm.SugarContext.init(SugarContext.java:31)
                                                               at ir.winwin.model.MyApplication.onCreate(MyApplication.java:12)
                                                               at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
                                                               at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4344)
                                                               at android.app.ActivityThread.access$1500(ActivityThread.java:135)
                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                                               at android.os.Looper.loop(Looper.java:136)
                                                               at android.app.ActivityThread.main(ActivityThread.java:5017)
                                                               at java.lang.reflect.Method.invokeNative(Native Method)
                                                               at java.lang.reflect.Method.invoke(Method.java:515)
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
                                                               at dalvik.system.NativeStart.main(Native Method)

**Comment by alexluckyq** [comment]
Hi, I have exact same issue. Have you found any solutions?

**Comment by patedit** [comment]
+1

**Comment by jppasa** [comment]
Also the same issue. Any tips?

**Comment by mohsenti** [comment]
+1
