### ISSUE TITLE
exception: database is locked

### ISSUE THREAD

**Issue by felipeaugusto1** [satyan/sugar#674]
Hello, I'm getting this exception when trying to run an upgrade script on my app. 

`Caused by android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5)`

Does anyone know why could be happening?

**Comment by hearbeathorror** [comment]
I face this same issue. Is there a workaround to this one? @felipeaugusto1 did you fix this somehow?

**Comment by felipeaugusto1** [comment]
I didn't. Have no idea why this is happening.

**Comment by andrelramos** [comment]
I have the same problem. I think this occurs because the application has multiple threads accessing the database.

```jsx
Fatal Exception: android.database.sqlite.SQLiteDatabaseLockedException: database is locked
       at android.database.sqlite.SQLiteDatabase.native_setLocale(SQLiteDatabase.java)
       at android.database.sqlite.SQLiteDatabase.setLocale(SQLiteDatabase.java:2074)
       at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1014)
       at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:986)
       at android.database.sqlite.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:1051)
       at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:781)
       at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:221)
       at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:157)
       at com.orm.SugarDb.getDB(SugarDb.java:58)
       at com.orm.SugarRecord.getSugarDataBase(SugarRecord.java:30)
       at com.orm.SugarRecord.find(SugarRecord.java:206) 
```

**Comment by sailingcat** [comment]
FYI : got it from BroadcastReceiver. Could we configure single connection or something that could help us with this multi thread pb ? 

java.lang.RuntimeException:
  at android.app.LoadedApk$ReceiverDispatcher$Args.run (LoadedApk.java:1235)
  at android.os.Handler.handleCallback (Handler.java:761)
  at android.os.Handler.dispatchMessage (Handler.java:98)
  at android.os.Looper.loop (Looper.java:156)
  at android.app.ActivityThread.main (ActivityThread.java:6623)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:942)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:832)
Caused by: android.database.sqlite.SQLiteDatabaseLockedException:
  at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId (Native Method)
  at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId (SQLiteConnection.java:818)
  at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId (SQLiteSession.java:803)
  at android.database.sqlite.SQLiteStatement.executeInsert (SQLiteStatement.java:86)
  at android.database.sqlite.SQLiteDatabase.insertWithOnConflict (SQLiteDatabase.java:1727)
  at com.orm.SugarRecord.save (SugarRecord.java:280)
  at com.orm.SugarRecord.save (SugarRecord.java:416)
  at com.xxx.calendar.model.web_services.ExchangeSyncAdapter$1.onReceive (ExchangeSyncAdapter.java:267)
  at android.app.LoadedApk$ReceiverDispatcher$Args.run (LoadedApk.java:1222)
