### ISSUE TITLE
NullPointerException: expected receiver of type <Table Class>, but got null

### ISSUE THREAD

**Issue by bioker** [satyan/sugar#676]
Hello, I have a next issue, what you think about it?

build.gradle:

```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 24
    buildToolsVersion "24.0.1"

    defaultConfig {
        applicationId "net.bioker.android.test"
        minSdkVersion 15
        targetSdkVersion 24
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:24.1.1'
    compile 'com.github.satyan:sugar:1.5'
}
```

AndroidManifest.xml:

```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="net.bioker.android.test">

    <application
        android:name="com.orm.SugarApp"
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:supportsRtl="true"
        android:theme="@style/AppTheme">
        <meta-data
            android:name="DATABASE"
            android:value="test.db" />
        <meta-data
            android:name="VERSION"
            android:value="1" />
        <meta-data
            android:name="QUERY_LOG"
            android:value="true" />
        <meta-data
            android:name="DOMAIN_PACKAGE_NAME"
            android:value="net.bioker.android.test" />
        <activity android:name=".MainActivity">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>

</manifest>
```

Target.java:

```
package net.bioker.android.test.orm;

import com.orm.dsl.Table;

@Table
public class Target {

    private Long id;
    private String name;
    private Target origin;

    public Target() {
    }

    public Target(String name) {
        this.name = name;
    }

    public Target(Long id, String name, Target origin) {
        this.id = id;
        this.name = name;
        this.origin = origin;
    }

    public Long getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public Target getOrigin() {
        return origin;
    }
}
```

MainActivity.java:

```
package net.bioker.android.test;

import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;

import com.orm.SugarContext;
import com.orm.SugarRecord;

import net.bioker.android.test.orm.Target;

public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        SugarContext.init(this);
        Target target = new Target("target");
        SugarRecord.save(target);
    }
}
```

and I getting stacktrace when I run my application on my device ASUS_T00J Android 4.4.2 or emulators with Android 4.1.1 and 4.4.4:

```
FATAL EXCEPTION: main
 Process: net.bioker.android.test, PID: 20993
 java.lang.RuntimeException: Unable to start activity ComponentInfo{net.bioker.android.test/net.bioker.android.test.MainActivity}: java.lang.NullPointerException: expected receiver of type net.bioker.android.test.orm.Target, but got null
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2318)
 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2396)
 at android.app.ActivityThread.access$800(ActivityThread.java:139)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1293)
 at android.os.Handler.dispatchMessage(Handler.java:102)
 at android.os.Looper.loop(Looper.java:149)
 at android.app.ActivityThread.main(ActivityThread.java:5257)
 at java.lang.reflect.Method.invokeNative(Native Method)
 at java.lang.reflect.Method.invoke(Method.java:515)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
 at dalvik.system.NativeStart.main(Native Method)
  Caused by: java.lang.NullPointerException: expected receiver of type net.bioker.android.test.orm.Target, but got null
 at java.lang.reflect.Field.getField(Native Method)
 at java.lang.reflect.Field.get(Field.java:266)
 at com.orm.util.ReflectionUtil.addFieldValueToColumn(ReflectionUtil.java:76)
 at com.orm.SugarRecord.save(SugarRecord.java:269)
 at com.orm.SugarRecord.save(SugarRecord.java:260)
 at net.bioker.android.test.MainActivity.onCreate(MainActivity.java:19)
 at android.app.Activity.performCreate(Activity.java:5411)
 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2270)
 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2396) 
 at android.app.ActivityThread.access$800(ActivityThread.java:139) 
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1293) 
 at android.os.Handler.dispatchMessage(Handler.java:102) 
 at android.os.Looper.loop(Looper.java:149) 
 at android.app.ActivityThread.main(ActivityThread.java:5257) 
 at java.lang.reflect.Method.invokeNative(Native Method) 
 at java.lang.reflect.Method.invoke(Method.java:515) 
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609) 
 at dalvik.system.NativeStart.main(Native Method) 
```

**Comment by sibelius** [comment]
fixed here: https://github.com/satyan/sugar/pull/677
