### ISSUE TITLE
java.lang.IllegalMonitorStateException in find

### ISSUE THREAD

**Issue by Anfet** [satyan/sugar#695]
Hello.

Any idea what can cause this error? 
`java.lang.IllegalMonitorStateException
	at java.util.concurrent.locks.ReentrantLock$Sync.tryRelease(ReentrantLock.java:126)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.release(AbstractQueuedSynchronizer.java:1239)
	at java.util.concurrent.locks.ReentrantLock.unlock(ReentrantLock.java:431)
	at android.database.sqlite.SQLiteDatabase.unlock(SQLiteDatabase.java:510)
	at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:62)
	at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1686)
	at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1571)
	at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1527)
	at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1645)
	at com.orm.SugarRecord.find(SugarRecord.java:201)
	at com.orm.SugarRecord.findById(SugarRecord.java:135)
	at com.orm.SugarRecord.findById(SugarRecord.java:141)
	at net.anfet.f.orders.support.Presenter.<init>(Presenter.java:71)

Happened few times already.`

**Comment by DarkLord44** [comment]
Seems like reading objects from the database makes a little bit of trouble. Would be nice if you post your code here, so we can further help you.

**Comment by Anfet** [comment]
Hm. as you can see, its simply a query to DB. Not even sure what you expect to see past main calling function.

**Comment by DarkLord44** [comment]
Well, if you dont give additional Information nobody want and can help you. Sorry.

**Comment by Anfet** [comment]
I simply don't know what you expect to see here.

Complete stacktrace?
`
java.lang.IllegalMonitorStateException
	at java.util.concurrent.locks.ReentrantLock$Sync.tryRelease(ReentrantLock.java:126)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.release(AbstractQueuedSynchronizer.java:1239)
	at java.util.concurrent.locks.ReentrantLock.unlock(ReentrantLock.java:431)
	at android.database.sqlite.SQLiteDatabase.unlock(SQLiteDatabase.java:487)
	at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:62)
	at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1564)
	at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1449)
	at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1405)
	at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1523)
	at com.orm.SugarRecord.find(SugarRecord.java:201)
	at com.orm.SugarRecord.findById(SugarRecord.java:135)
	at com.orm.SugarRecord.findById(SugarRecord.java:141)
	at net.anfet.f.orders.support.Presenter.<init>(Presenter.java:73)
	at net.anfet.f.orders.fOrders.onAfterInflate(fOrders.java:415)
	at net.anfet.simple.support.library.SupportFragment.onCreateView(SupportFragment.java:94)
	at android.support.v4.app.Fragment.performCreateView(Fragment.java:2087)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1113)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1295)
	at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:801)
	at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:1643)
	at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:679)
	at android.support.v4.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:166)
	at android.support.v4.view.ViewPager.populate(ViewPager.java:1272)
	at android.support.v4.view.ViewPager.populate(ViewPager.java:1120)
	at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1646)
	at android.view.View.measure(View.java:12773)
	at android.support.v4.widget.DrawerLayout.onMeasure(DrawerLayout.java:1081)
	at android.view.View.measure(View.java:12773)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4788)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1374)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:663)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:553)
	at android.view.View.measure(View.java:12773)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4788)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:293)
	at android.view.View.measure(View.java:12773)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4788)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:293)
	at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
	at android.view.View.measure(View.java:12773)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4788)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1374)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:663)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:553)
	at android.view.View.measure(View.java:12773)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4788)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:293)
	at android.view.View.measure(View.java:12773)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4788)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1374)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:663)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:553)
	at android.view.View.measure(View.java:12773)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4788)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:293)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2103)
	at android.view.View.measure(View.java:12773)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1149)
	at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2564)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:4508)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:809)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:576)
	at dalvik.system.NativeStart.main(Native Method)
`

Calling code:
`
hideOrdersOnTicket = SugarRecord.findById(ConfigEntry.class, ConfigEntry.CONFIG_HIDE_ORDERS_ON_TICKET).asBoolean();
`
And it's not very frequently appearing. Perhaps on 4.0.4 androids.

**Comment by Anfet** [comment]
in 1.5 this erorr is still festering on 4.0.4 android systems

`
java.util.concurrent.locks.ReentrantLock$Sync.tryRelease (ReentrantLock.java:126)
java.util.concurrent.locks.AbstractQueuedSynchronizer.release (AbstractQueuedSynchronizer.java:1239)
java.util.concurrent.locks.ReentrantLock.unlock (ReentrantLock.java:431)
android.database.sqlite.SQLiteDatabase.unlock (SQLiteDatabase.java:487)
android.database.sqlite.SQLiteDirectCursorDriver.query (SQLiteDirectCursorDriver.java:62)
android.database.sqlite.SQLiteDatabase.rawQueryWithFactory (SQLiteDatabase.java:1564)
android.database.sqlite.SQLiteDatabase.queryWithFactory (SQLiteDatabase.java:1449)
android.database.sqlite.SQLiteDatabase.query (SQLiteDatabase.java:1405)
android.database.sqlite.SQLiteDatabase.query (SQLiteDatabase.java:1523)
com.orm.SugarRecord.find (SugarRecord.java:201)
com.orm.SugarRecord.listAll (SugarRecord.java:127)
net.anfet.AMain.onLocationChanged (AMain.java:986)
java.lang.reflect.Method.invokeNative (Method.java)
java.lang.reflect.Method.invoke (Method.java:511)
`
