### ISSUE TITLE
Getting no such table error with Sugarorm 1.4 in android

### ISSUE THREAD

**Issue by iot007** [satyan/sugar#715]
I am getting the following error while I am trying to perform CRUD operations on my db using sugarorm:

```
E/SQLiteLog: (1) no such table: CONTACT D/AndroidRuntime: Shutting down VM E/AndroidRuntime: FATAL EXCEPTION: main
              Process: com.example.sinha.abhishek.demoapp, PID: 2133
              android.database.sqlite.SQLiteException: no such table: CONTACT (code 1): , while compiling: SELECT * FROM CONTACT WHERE id=? LIMIT 1
                  at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
                  at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
                  at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
                  at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
                  at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
                  at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
                  at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
                  at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1316)
                  at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1163)
                  at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1034)
                  at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1240)
                  at com.orm.SugarRecord.find(SugarRecord.java:192)
                  at com.orm.SugarRecord.findById(SugarRecord.java:102)
                  at com.example.sinha.abhishek.demoapp.Contact.<init>(Contact.java:31)
                  at com.example.sinha.abhishek.demoapp.MainActivity$1.onClick(MainActivity.java:48)
                  at android.view.View.performClick(View.java:4785)
                  at android.view.View$PerformClick.run(View.java:19888)
                  at android.os.Handler.handleCallback(Handler.java:739)
                  at android.os.Handler.dispatchMessage(Handler.java:95)
                  at android.os.Looper.loop(Looper.java:135)
                  at android.app.ActivityThread.main(ActivityThread.java:5276)
                  at java.lang.reflect.Method.invoke(Native Method)
                  at java.lang.reflect.Method.invoke(Method.java:372)
                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:911)
                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:706) 
```

Can anybody please guide, what might be the probable cause for this and how can it be fixed.

This is my pojo class:

```
public class Contact extends SugarRecord{

     int contactid;
     String firstName;
     String lastName;
     int age;
     String address;
     String phone;

    public Contact(){
        super();
    }

    public Contact(int contactid, String firstName, String lastName, int age, String address, String phone){
        this.contactid = contactid;
        this.firstName = firstName;
        this.lastName = lastName;
        this.age = age;
        this.address = address;
        this.phone= phone;

    }


}
```

This is my android manifest file:

```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.sinha.abhishek.demoapp">

    <application
        android:name="com.orm.SugarApp"
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:supportsRtl="true"
        android:theme="@style/AppTheme">



        <activity android:name=".MainActivity">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>


        <meta-data
            android:name="DATABASE"
            android:value="hollywoodcontacts.db" />
        <meta-data
            android:name="VERSION"
            android:value="2" />
        <meta-data
            android:name="QUERY_LOG"
            android:value="true" />
        <meta-data
            android:name="DOMAIN_PACKAGE_NAME"
            android:value="com.example.sinha.abhishek.demoapp" />



    </application>

</manifest>
```

This is my sample code for CRUD operation written within main activity:

```
Contact  con  = new Contact(101 ,"Abcd","Xyz",22,"myaddress", "9849848943");
con.save();
```

I have already tried options like: 
1. Disabling instant run 
2. Contact.findById(Contact.class, (long) 1);

but none of then worked for me.

**Comment by yohaybn** [comment]
I has this issue too, and I found that If I change the model fields, I need to change the db version.. Even if I deleted the app and reinstall it...

**Comment by peterchaula** [comment]
>Even if I deleted the app and reinstall it..

@yohaybn that doesn't make a lot of sense to me. I thought if we reinstall the app we would be starting on a clean slate

**Comment by eduardoadcj** [comment]
I resolved my problem using the version 2.2.0 of gradle

**Comment by karuhanga** [comment]
Good to hear.
Kindly close the issue.

**Comment by irfan1205** [comment]
Error Code : 1 (SQLITE_ERROR)
                  Caused By : SQL(query) error or missing database.
                  	(no such table: OrderDetail (code 1): , while compiling: INSERT INTO OrderDetail

**Comment by karuhanga** [comment]
Hello,
I think your issue stems from the naming conventions.
The `OrderDetail` class would be ORDER_DETAIL in the db.
To get the default SQL name of a table you can always use the `NamingHelper.toSQLName(TableName.class)`.
The for fields `NamingHelper.toSQLNameDefault("fieldName")`

**Comment by aluckens** [comment]
The domain package name should match the package where you put the models/entities  (class you want to generate table for)

for example:
<meta-data
            android:name="DOMAIN_PACKAGE_NAME"
            android:value="com.example.sinha.abhishek.demoapp.model" />

don't forget to unistall the app after the changes before running again
