### ISSUE TITLE
SQLiteException: no such table

### ISSUE THREAD

**Issue by ArtanisHong** [satyan/sugar#734]
I created the project with sugar orm but it even cannot create all tables.

## this is my manifest config:
`<meta-data android:name="DATABASE" android:value="app.db"/>
        <meta-data android:name="VERSION" android:value="1"/>
        <meta-data android:name="QUERY_LOG" android:value="true"/>
        <meta-data android:name="DOMAIN_PACKAGE_NAME" android:value="com.example.beedom.model"/>`

## this is my model definition:
`@Table(name = "courses")
public class Course extends SugarRecord implements Parcelable {

    private int imageId;
    private int teacher_avatarId;
    private int colorId ;
    private String period;
    private String name;
    private String place;
    private String teacher;
    private String brief;
    private String saying;

    public Course() {}
    ......
}
`
I have tried all the solutions such as increase the DB version or close the instant-run. And my App class
already has extended the SugarApp. Now I need your help T_T. @satyan

**Comment by rrigoni** [comment]
Same issue here. The app started crashing from no reason. 
Instant run is disabled. 

````
Connected` to the target VM, address: 'localhost:8603', transport: 'socket'
android.database.sqlite.SQLiteException: no such table: ENVIRONMENT (code 1): , while compiling: SELECT * FROM ENVIRONMENT
	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
	at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
	at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
	at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1318)
	at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1165)
	at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1036)
	at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1242)
````

**Comment by caojianhua** [comment]
Must add the code as below, and not such error on Android 5.0
```
<meta-data android:name="DOMAIN_PACKAGE_NAME" android:value="MODELS PACKAGE NAME"/>
```

**Comment by DaTigerZ** [comment]
ok, I think this kind of problems should be put on to the Offical webpage as a trouble shooting sector!!!
in file  AndroidManifest.xml
`<meta-data android:name="VERSION" android:value="3" />`  I just made a change ` value=2`
to  ` value=3`. it works.

**Comment by masoomyf** [comment]
Facing same issue.
```
Caused by: android.database.sqlite.SQLiteException: no such table: CLASS_ROUTINE (code 1): , while compiling: SELECT * FROM CLASS_ROUTINE
                                                                             at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
                                                                             at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:887)
                                                                             at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:498)
                                                                             at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
                                                                             at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
                                                                             at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
                                                                             at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
                                                                             at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1316)
                                                                             at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1163)
                                                                             at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1034)
                                                                             at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1240)
                                                                             at com.orm.SugarRecord.find(SugarRecord.java:208)
                                                                             at com.orm.SugarRecord.listAll(SugarRecord.java:134)
```

**Comment by karuhanga** [comment]
Did you uninstall and then reinstall the app after disabling IR?

**Comment by DaTigerZ** [comment]
In my case.
I copied my code(entire project) to another computer. than it show me error messages and told me no such table.
I solved the case by modify following setting:
```
locate file name: **AndroidManifest.xml**

FIND:
<meta-data android:name="VERSION" android:**value="3"** />

CHANGE:
 android:value="3" TO  **android:value="2"**

then it works with my project.
```
It is kind of version contorl requirements i guess.

**Comment by Vaflan** [comment]
I imagine this may be fixed shortly, but for this to work in the meantime, you should disable the feature in the following menu

`File | Settings | Build, Execution, Deployment | Instant Run`

Cleaning and then building the application should resolve these issues.

You can see the reason in stackoverflow [here](https://stackoverflow.com/a/35942765/3778527)
