### ISSUE TITLE
Failed to read row 0, column -1 from a CursorWindow which has

### ISSUE THREAD

**Issue by walisonbh** [satyan/sugar#763]
Hello friends!

Could anyone clarify the reason for this error?

```
package br.com.wlsolucoes.xxxxxxxxxxxx.Model.Entity;

import com.orm.dsl.Table;

@Table(name = "cores_veiculos")
public class CorVeiculo {
	private Long id;
	private String nome;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getNome() {
		return nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String toString() {
		return nome;
	}
}
```

`findWithQuery(CorVeiculo.class, "Select id, nome from cores_veiculos")`

> SQLiteQuery: Select id, nome from cores_veiculos
 Failed to read row 0, column -1 from a CursorWindow which has 16 rows, 2 columns.
 java.lang.IllegalStateException: Couldn't read row 0, col -1 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
     at android.database.CursorWindow.nativeGetLong(Native Method)
     at android.database.CursorWindow.getLong(CursorWindow.java:511)
     at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:75)
     at com.orm.SugarRecord.inflate(SugarRecord.java:354)
     at com.orm.SugarRecord.getEntitiesFromCursor(SugarRecord.java:213)
     at com.orm.SugarRecord.findWithQuery(SugarRecord.java:193)
     at br.com.wlsolucoes.xxxxxxxxxxxx.Fragment.CadastrarDadosVeiculoFragment.montarAutoCompleteTextView(CadastrarDadosVeiculoFragment.java:245)
     at br.com.wlsolucoes.xxxxxxxxxxxx.Fragment.CadastrarDadosVeiculoFragment.onStart(CadastrarDadosVeiculoFragment.java:214)
     at android.support.v4.app.Fragment.performStart(Fragment.java:2218)
     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1340)
     at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
     at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:758)
     at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2363)
     at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2149)
     at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103)
     at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2013)
     at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:710)
     at android.os.Handler.handleCallback(Handler.java:739)
     at android.os.Handler.dispatchMessage(Handler.java:95)
     at android.os.Looper.loop(Looper.java:135)
     at android.app.ActivityThread.main(ActivityThread.java:5254)
     at java.lang.reflect.Method.invoke(Native Method)
     at java.lang.reflect.Method.invoke(Method.java:372)
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

Thank you!

**Comment by esdeguzman** [comment]
Any updates here?

**Comment by Bartoloni** [comment]
i've the same issue... no one with an answer?

**Comment by webwarrior06** [comment]
I have too. My class is like following;
```
@Table(name = "Leagues")
class League() : ICriteria {

    @Column(name = "Club_ID")
    var ClubId :Int = 0
    @Column(name = "Club")
    var Club :String = ""
    @Column(name = "League")
    var League:String = ""
    @Ignore
    override var isSelected: Boolean = false
    @Ignore
    override lateinit var itemName: String
}
```
I try to list the items with this line;
`itemList = Select.from(League::class.java).groupBy("League").toMutableList() as MutableList<League>`

Items retrieved, but properties are set to null.

**Comment by CleatonPais** [comment]
has the same problem
what did it for me instead of using .findWithQuery() use find() or findAll()
