### ISSUE TITLE
java.lang.NullPointerException: null receiver

### ISSUE THREAD

**Issue by Tindi** [satyan/sugar#771]
Hi I'm getting the following error when saving my data. I have used Sugar before and I have set up everything as explained.

Log Cat shows:
`Creating table QUESTION
I/Sugar: Create table if not exists
D/Sugar: Fetching properties
I/Sugar: Question saved : 1`

it then crashes with:

`E/AndroidRuntime: FATAL EXCEPTION: main
                                                                 Process: com.my.app, PID: 20051
                                                                 java.lang.NullPointerException: null receiver
                                                                     at java.lang.reflect.Field.get(Native Method)
                                                                     at java.lang.reflect.Field.get(Field.java:279)
                                                                     at com.orm.util.ReflectionUtil.addFieldValueToColumn(ReflectionUtil.java:76)
                                                                     at com.orm.SugarRecord.save(SugarRecord.java:269)
                                                                     at com.orm.SugarRecord.save(SugarRecord.java:260)
                                                                     at com.my.app.ui.LoginActivity$GetQuestionsTask.onPostExecute(LoginActivity.java:284)
                                                                     at com.my.app.ui.LoginActivity$GetQuestionsTask.onPostExecute(LoginActivity.java:263)
                                                                     at android.os.AsyncTask.finish(AsyncTask.java:636)
                                                                     at android.os.AsyncTask.access$500(AsyncTask.java:177)
                                                                     at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                     at android.os.Looper.loop(Looper.java:135)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5910)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)`

What could be happening? Could it be that some fields from my API have null values? Thanks.

**Comment by kigen** [comment]
Can you please post your model here. 
There might be a problem with your model (fields)
