### ISSUE TITLE
Error in null value for Date field

### ISSUE THREAD

**Issue by jmtt89** [satyan/sugar#783]
Hi, i see a closed thread about recording null date's error, solved for version 1.4 (https://github.com/chennaione/sugar/issues/178)  but in version 1.5 i have the same error

```
TransactionDatabase: add: java.lang.NullPointerException: Attempt to invoke virtual method 'long java.util.Date.getTime()' on a null object reference
                                                                           at com.orm.SugarRecord.save(SugarRecord.java:109)
                                                                           at com.orm.SugarRecord.save(SugarRecord.java:45)
```

Thks.

**Comment by karuhanga** [comment]
Kindly give us a look at both your class and the code causing the issue.
