### ISSUE TITLE
Sugar ORM thrown no such table error when minifyEnable true

### ISSUE THREAD

**Issue by deepmindbd** [satyan/sugar#788]
Is Anyone facing this problem? 

I am using version 1.5 

> com.github.satyan:sugar:1.5

Error:

`android.database.sqlite.SQLiteException: no such table: tbl_user (code 1): , while compiling: DELETE FROM tbl_user
                                                       at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
                                                       at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
                                                       at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
                                                       at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
                                                       at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
                                                       at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
                                                       at android.database.sqlite.SQLiteDatabase.delete(SQLiteDatabase.java:1497)
                                                       at com.e.d.a(Unknown Source)
                                                       at com.e.d.a(Unknown Source)`

I already tried by changing db name with version value. Instant run is also disabled.

Is there any solution?

**Comment by hzhdeveloper** [comment]
you need uninstall app and re install newest app

**Comment by prameshbajra** [comment]
Hey @deepmindbd 
Did you find a solution to this?

I am facing the same error and for it it works in debug mode but not on release mode. Any ideas?

Thank you 🙏🏽
