### ISSUE TITLE
findAll return Empty List next to add MultiDex and upgrade to sugar 1.4 to 1.5

### ISSUE THREAD

**Issue by hellfish90** [satyan/sugar#790]
I have this application in production with the sugar version 1.4 without Multidex and it's works, but when I upgraded sugar orm to 1.5 and I added Multidex like this:

```
public class MyApplication extends SugarApp{

@Override
    protected void attachBaseContext(Context context) {
        super.attachBaseContext(context);
        MultiDex.install(this);
    }
}
```

AndroidManifest.xml
```
<application
        android:name=".MyApplication">
<application/>
```

build.gradle

```
android {
    defaultConfig {
        multiDexEnabled true
    }
}


dependencies {

compile 'com.github.satyan:sugar:1.5'
compile 'com.android.support:multidex:1.0.1'
}

```

And with a new installation of the app it's creates the tables and save the entities i cannot retrieve the data when I call:

```
EventType.listAll(EventType.class)
```

Returns and empty list with this error:

```
SQLiteQuery: SELECT * FROM EVENT_TYPE
W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.hashCode()' on a null object reference
W/System.err:     at com.blabla.Models.Event.EventType.hashCode(EventType.java:87)
W/System.err:     at sun.misc.Hashing.singleWordWangJenkinsHash(Hashing.java:48)
```

And when I call:

```
Lists.newArrayList(EventType.findAll(EventType.class))
```

Returns and array with the attr null but with the size of the registers that I have in the db:

```
DAODBEventType: SAVE:[Type{name='null'}, Type{name='null'}, Type{name='null'}, Type{name='null'}, Type{name='null'}, Type{name='null'}, Type{name='null'}, Type{name='null'}, Type{name='null'}, Type{name='null'}, Type{name='null'}, Type{name='null'}, Type{name='null'}, Type{name='null'}]
```

The model of EventType:
```
public class EventType  extends SugarRecord implements Type{

    @SerializedName("id")
    private Long identifier;
    @SerializedName("name")
    private String name;
    @SerializedName("image")
    private String image;

    private boolean selected= false;

    public EventType() {
    }

```
I verified that I have registers in the database and also I have the Sugar Log that verify the entry:
```
I/Sugar: EventType saved : 1
I/Sugar: EventType saved : 2
I/Sugar: EventType saved : 3
I/Sugar: EventType saved : 4
I/Sugar: EventType saved : 5
I/Sugar: EventType saved : 6
I/Sugar: EventType saved : 7
I/Sugar: EventType saved : 8
I/Sugar: EventType saved : 9
I/Sugar: EventType saved : 10
I/Sugar: EventType saved : 11
I/Sugar: EventType saved : 12
I/Sugar: EventType saved : 13
I/Sugar: EventType saved : 14
```

Someone has been found with a similar problem, any suggestions? Thank you

**Comment by hsosa88** [comment]
I have same issue, any solution?

**Comment by iaubain** [comment]
`public class Application extends SugarApp {
    @Override
    public void onCreate() {
        super.onCreate();
        SugarContext.init(getApplicationContext());

        // create table if not exists
        SchemaGenerator schemaGenerator = new SchemaGenerator(this);
        schemaGenerator.createDatabase(new SugarDb(this).getDB());
    }

    @Override
    public void onConfigurationChanged(Configuration newConfig) {
        super.onConfigurationChanged(newConfig);
    }

    @Override
    public void onLowMemory() {
        super.onLowMemory();
    }

    @Override
    public void onTerminate() {
        super.onTerminate();
        //SugarContext.terminate();
    }
}`

That is how my Application looks like. Hope It will help
