### ISSUE TITLE
Testing Sugar

### ISSUE THREAD

**Issue by jivimberg** [satyan/sugar#96]
Hi I was wondering if anyone was able to make sugar work with Robolectric.
I wrote a save tests and keep getting

```
java.lang.NullPointerException
	at dalvik.system.DexFile$DFEnum.hasMoreElements(DexFile.java:239)
	at com.orm.SugarDb.getDomainClasses(Unknown Source)
	at com.orm.SugarDb.createDatabase(Unknown Source)
	at com.orm.SugarDb.onCreate(Unknown Source)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:252)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:164)
	at com.orm.Database.openDB(Unknown Source)
	at com.orm.SugarRecord.save(Unknown Source)
```

Any pointer would be appreciated

**Comment by loose11** [comment]
I get the same error. My dependency is  compile 'com.github.satyan:sugar:1.3' . what can I do?

**Comment by dominicwong617** [comment]
+1

**Comment by loose11** [comment]
I have the solution. Easy as hell. 
You have to great an package com.orm with the class TestSugarApp. The Class looks like this:

    @RunWith(RobolectricTestRunner.class)
    @Config(manifest="./src/main/AndroidManifest.xml",emulateSdk=18)
    public class TestSugarApp extends Application
        implements TestLifecycleApplication {



    @Test
    public void startEverTestSugarAppAsFirst() {

    }

    @Override
    public void beforeTest(Method method) {
        Log.v("test", "beforeTest");
    }

    @Override
    public void prepareTest(Object test) {
        Log.v("test", "prepareTest");
    }

    @Override
    public void afterTest(Method method) {
        Log.v("test", "afterTest");
    }
}


After that all tests worked out for me :)

**Comment by leenasn** [comment]
Does it make sense to add a it as part of the Wiki. If yes, I can submit a pull request for the same.

**Comment by loose11** [comment]
Make sense +1

**Comment by leenasn** [comment]
ok. @loose11 are you taking care of the same?

**Comment by clay-to-n** [comment]
@loose11, I've created that package in test/java, and made that file (with imports and "package com.orm;" at the top) in my project.

I still get the same error, even in that new test file.  On sugar 1.3.1.  Any idea what I could be missing?

**Comment by pickeyboy** [comment]
@loose11 I face exactly the same problem @clay-to-n is facing. Is there any solution ? 

My Application class is also extending SugarApp and I get the same exception even after adding TestSugarApp under com.orm package.
